# filename: india_stock_advisor_complete.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import numpy as np
import warnings
import time
import os
warnings.filterwarnings('ignore')

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils.dataframe import dataframe_to_rows
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False
    print("⚠️  openpyxl not found. Installing for Excel formatting...")
    os.system('pip install openpyxl')
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils.dataframe import dataframe_to_rows
        OPENPYXL_AVAILABLE = True
    except:
        OPENPYXL_AVAILABLE = False

class HighConfidenceStockAdvisor:
    def __init__(self, investment_capital=100000, min_confidence=80):
        self.nse_stocks = [
            'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
            'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
            'LT.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'MARUTI.NS', 'TITAN.NS',
            'SUNPHARMA.NS', 'ULTRACEMCO.NS', 'NESTLEIND.NS', 'BAJFINANCE.NS', 'WIPRO.NS',
            'HCLTECH.NS', 'TECHM.NS', 'POWERGRID.NS', 'NTPC.NS', 'ONGC.NS',
            'TATASTEEL.NS', 'ADANIENT.NS', 'JSWSTEEL.NS', 'GRASIM.NS', 'HINDALCO.NS',
            'DIVISLAB.NS', 'DRREDDY.NS', 'CIPLA.NS', 'EICHERMOT.NS', 'HEROMOTOCO.NS',
            'M&M.NS', 'BAJAJFINSV.NS', 'TATACONSUM.NS', 'INDUSINDBK.NS', 'COALINDIA.NS',
            'BRITANNIA.NS', 'APOLLOHOSP.NS', 'PIDILITIND.NS', 'DABUR.NS', 'GODREJCP.NS',
            'ADANIPORTS.NS', 'SHREECEM.NS', 'BPCL.NS', 'IOC.NS', 'VEDL.NS',
            'TORNTPHARM.NS', 'LUPIN.NS', 'BIOCON.NS', 'BAJAJ-AUTO.NS', 'HAVELLS.NS',
            'SIEMENS.NS', 'DLF.NS', 'GAIL.NS', 'AMBUJACEM.NS', 'ACC.NS',
            'TATAPOWER.NS', 'ADANIGREEN.NS', 'BANDHANBNK.NS', 'INDUSTOWER.NS', 'PNB.NS',
            'SAIL.NS', 'NMDC.NS', 'RECLTD.NS', 'IDEA.NS', 'ZEEL.NS',
            'MOTHERSON.NS', 'BALKRISIND.NS', 'BOSCHLTD.NS', 'ABCAPITAL.NS', 'MPHASIS.NS',
            'BERGEPAINT.NS', 'PAGEIND.NS', 'COLPAL.NS', 'MARICO.NS', 'PERSISTENT.NS',
            'MCDOWELL-N.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'ICICIPRULI.NS', 'BAJAJHLDNG.NS',
            'SBICARD.NS', 'TRENT.NS', 'ZOMATO.NS', 'NYKAA.NS', 'PAYTM.NS',
            'DMART.NS', 'IRCTC.NS', 'PGHH.NS', 'INDIGO.NS', 'VOLTAS.NS',
            'CUMMINSIND.NS', 'COFORGE.NS', 'LTIM.NS', 'TATAELXSI.NS', 
            'CROMPTON.NS', 'JUBLFOOD.NS', 'GODREJPROP.NS', 'OBEROIRLTY.NS', 'PRESTIGE.NS'
        ]
        
        self.investment_capital = max(investment_capital, 1000)
        self.min_confidence = max(min(min_confidence, 100), 50)
        self.stock_data = {}
        self.analyzed_stocks = []
        self.today = datetime.now()
        self.output_folder = f"stock_reports_{self.today.strftime('%Y%m%d_%H%M')}"
        
        if not os.path.exists(self.output_folder):
            os.makedirs(self.output_folder)
    
    def fetch_latest_stock_data(self):
        print(f"Fetching LATEST data from {len(self.nse_stocks)} NSE stocks...")
        print(f"Data retrieval time: {self.today.strftime('%Y-%m-%d %H:%M:%S IST')}")
        print("=" * 80)
        
        successful = 0
        failed = 0
        
        for idx, symbol in enumerate(self.nse_stocks, 1):
            try:
                print(f"[{idx}/{len(self.nse_stocks)}] {symbol}...", end=' ')
                
                stock = yf.Ticker(symbol)
                hist_6m = stock.history(period='6mo')
                
                if hist_6m.empty or len(hist_6m) < 30:
                    print(f"✗ Insufficient data")
                    failed += 1
                    continue
                
                try:
                    hist_1d = stock.history(period='1d', interval='1m')
                except:
                    hist_1d = pd.DataFrame()
                
                try:
                    info = stock.info
                    company_name = info.get('longName', symbol.replace('.NS', ''))
                except:
                    company_name = symbol.replace('.NS', '')
                
                current_price = hist_6m['Close'].iloc[-1]
                
                if not hist_1d.empty and len(hist_1d) > 0:
                    try:
                        current_price = hist_1d['Close'].iloc[-1]
                    except:
                        pass
                
                if pd.isna(current_price) or current_price <= 0:
                    print(f"✗ Invalid price")
                    failed += 1
                    continue
                
                self.stock_data[symbol] = {
                    'history': hist_6m,
                    'intraday': hist_1d,
                    'name': company_name,
                    'current_price': float(current_price),
                    'symbol': symbol,
                    'last_update': self.today
                }
                print(f"✓ ₹{current_price:.2f}")
                successful += 1
                
                if idx % 10 == 0:
                    time.sleep(1)
                
            except Exception as e:
                print(f"✗ Error")
                failed += 1
        
        print(f"\n{'='*80}")
        print(f"✓ Successfully loaded: {successful} stocks")
        print(f"✗ Failed to load: {failed} stocks")
        print(f"Total stocks for analysis: {len(self.stock_data)}")
        print(f"{'='*80}")
    
    def calculate_fibonacci_levels(self, hist):
        try:
            high = hist['High'].max()
            low = hist['Low'].min()
            diff = high - low
            
            if diff <= 0:
                return None
            
            return {
                'level_0': low,
                'level_23.6': low + (diff * 0.236),
                'level_38.2': low + (diff * 0.382),
                'level_50': low + (diff * 0.5),
                'level_61.8': low + (diff * 0.618),
                'level_78.6': low + (diff * 0.786),
                'level_100': high
            }
        except:
            return None
    
    def calculate_bollinger_bands(self, prices, period=20):
        try:
            if len(prices) < period:
                return None, None, None
            
            sma = prices.rolling(window=period).mean()
            std = prices.rolling(window=period).std()
            
            if pd.isna(sma.iloc[-1]) or pd.isna(std.iloc[-1]):
                return None, None, None
            
            upper_band = sma + (std * 2)
            lower_band = sma - (std * 2)
            
            return float(upper_band.iloc[-1]), float(sma.iloc[-1]), float(lower_band.iloc[-1])
        except:
            return None, None, None
    
    def calculate_momentum_score(self, hist):
        try:
            close = hist['Close']
            
            if len(close) < 20:
                return 0
            
            roc_5 = ((close.iloc[-1] - close.iloc[-5]) / close.iloc[-5]) * 100 if len(close) >= 5 else 0
            roc_10 = ((close.iloc[-1] - close.iloc[-10]) / close.iloc[-10]) * 100 if len(close) >= 10 else 0
            roc_20 = ((close.iloc[-1] - close.iloc[-20]) / close.iloc[-20]) * 100 if len(close) >= 20 else 0
            
            if len(hist) >= 20:
                vol_recent = hist['Volume'].iloc[-5:].mean()
                vol_past = hist['Volume'].iloc[-20:-5].mean()
                volume_ratio = vol_recent / vol_past if vol_past > 0 else 1
            else:
                volume_ratio = 1
            
            momentum = (roc_5 * 0.5) + (roc_10 * 0.3) + (roc_20 * 0.2) + (volume_ratio * 10)
            
            if pd.isna(momentum) or np.isinf(momentum):
                return 0
            
            return float(momentum)
        except:
            return 0
    
    def calculate_rsi(self, prices, period=14):
        try:
            if len(prices) < period + 1:
                return 50
            
            delta = prices.diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
            
            if loss.iloc[-1] == 0:
                return 100 if gain.iloc[-1] > 0 else 50
            
            rs = gain / loss
            rsi = 100 - (100 / (1 + rs))
            
            result = rsi.iloc[-1]
            if pd.isna(result) or np.isinf(result):
                return 50
            
            return float(max(0, min(100, result)))
        except:
            return 50
    
    def calculate_macd(self, prices):
        try:
            if len(prices) < 26:
                return 0, 0, 0
            
            exp1 = prices.ewm(span=12, adjust=False).mean()
            exp2 = prices.ewm(span=26, adjust=False).mean()
            macd = exp1 - exp2
            signal = macd.ewm(span=9, adjust=False).mean()
            histogram = macd - signal
            
            m = macd.iloc[-1]
            s = signal.iloc[-1]
            h = histogram.iloc[-1]
            
            if pd.isna(m) or pd.isna(s) or pd.isna(h):
                return 0, 0, 0
            
            return float(m), float(s), float(h)
        except:
            return 0, 0, 0
    
    def calculate_adx(self, hist, period=14):
        try:
            if len(hist) < period * 2:
                return 25
            
            high = hist['High']
            low = hist['Low']
            close = hist['Close']
            
            plus_dm = high.diff()
            minus_dm = -low.diff()
            plus_dm[plus_dm < 0] = 0
            minus_dm[minus_dm < 0] = 0
            
            tr1 = high - low
            tr2 = abs(high - close.shift())
            tr3 = abs(low - close.shift())
            tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
            
            atr = tr.rolling(window=period).mean()
            
            plus_di = 100 * (plus_dm.rolling(window=period).mean() / atr)
            minus_di = 100 * (minus_dm.rolling(window=period).mean() / atr)
            
            dx = 100 * abs(plus_di - minus_di) / (plus_di + minus_di + 0.0001)
            adx = dx.rolling(window=period).mean()
            
            result = adx.iloc[-1]
            if pd.isna(result) or np.isinf(result):
                return 25
            
            return float(max(0, min(100, result)))
        except:
            return 25
    
    def predict_entry_exit_dates(self, hist, current_price, signals):
        try:
            close = hist['Close']
            avg_daily_move = abs(close.pct_change()).mean()
            
            if pd.isna(avg_daily_move) or avg_daily_move <= 0:
                avg_daily_move = 0.01
            
            entry_date = self.today
            if signals['investment_timing'] == 'BUY NOW':
                entry_date = self.today + timedelta(days=1)
            elif signals['investment_timing'] == 'BUY ON DIP':
                days_diff = abs(current_price - signals['entry_point'])
                daily_move_amount = current_price * avg_daily_move
                days_to_wait = int(days_diff / daily_move_amount) if daily_move_amount > 0 else 5
                entry_date = self.today + timedelta(days=min(max(days_to_wait, 2), 7))
            elif signals['investment_timing'] == 'ACCUMULATE':
                entry_date = self.today + timedelta(days=2)
            else:
                entry_date = self.today + timedelta(days=7)
            
            price_to_target = abs(signals['target_1'] - current_price)
            daily_move = current_price * avg_daily_move
            
            if daily_move > 0:
                days_to_target = int(price_to_target / daily_move)
                days_to_target = min(max(days_to_target, 20), 90)
            else:
                days_to_target = 45
            
            exit_date = entry_date + timedelta(days=days_to_target)
            stop_loss_date = entry_date + timedelta(days=5)
            
            return {
                'entry_date': entry_date,
                'exit_date': exit_date,
                'stop_loss_check_date': stop_loss_date,
                'holding_days': days_to_target
            }
        except:
            return {
                'entry_date': self.today + timedelta(days=1),
                'exit_date': self.today + timedelta(days=45),
                'stop_loss_check_date': self.today + timedelta(days=5),
                'holding_days': 45
            }
    
    def generate_investment_signals(self, hist, current_price):
        try:
            close_prices = hist['Close']
            
            if len(close_prices) < 30:
                return None
            
            sma_20 = close_prices.rolling(window=20).mean().iloc[-1] if len(close_prices) >= 20 else current_price
            sma_50 = close_prices.rolling(window=50).mean().iloc[-1] if len(close_prices) >= 50 else current_price
            sma_200 = close_prices.rolling(window=200).mean().iloc[-1] if len(close_prices) >= 200 else current_price
            
            high_52w = hist['High'].max()
            low_52w = hist['Low'].min()
            
            support = hist['Low'].iloc[-30:].min()
            resistance = hist['High'].iloc[-30:].max()
            
            if pd.isna(support) or pd.isna(resistance) or resistance <= support:
                return None
            
            rsi = self.calculate_rsi(close_prices)
            macd, macd_signal, macd_hist = self.calculate_macd(close_prices)
            adx = self.calculate_adx(hist)
            
            bb_upper, bb_middle, bb_lower = self.calculate_bollinger_bands(close_prices)
            if bb_upper is None:
                bb_upper, bb_middle, bb_lower = resistance, current_price, support
            
            fib_levels = self.calculate_fibonacci_levels(hist)
            if fib_levels is None:
                return None
            
            price_range = resistance - support
            entry_point = support + (price_range * 0.12)
            profit_target_1 = fib_levels['level_61.8']
            profit_target_2 = resistance * 0.97
            stop_loss = support * 1.015
            
            if profit_target_1 <= current_price:
                profit_target_1 = current_price * 1.08
            
            investment_timing = "WAIT"
            timing_reason = ""
            risk_level = "MEDIUM"
            confidence_score = 50
            
            bullish_signals = 0
            total_signals = 0
            
            if current_price > sma_20:
                bullish_signals += 1
            total_signals += 1
            
            if current_price > sma_50:
                bullish_signals += 1
            total_signals += 1
            
            if sma_20 > sma_50:
                bullish_signals += 1
            total_signals += 1
            
            if macd > macd_signal:
                bullish_signals += 1
            total_signals += 1
            
            if macd_hist > 0:
                bullish_signals += 1
            total_signals += 1
            
            if 30 < rsi < 70:
                bullish_signals += 1
            total_signals += 1
            
            if adx > 25:
                bullish_signals += 1
            total_signals += 1
            
            if current_price > bb_lower and current_price < bb_upper:
                bullish_signals += 1
            total_signals += 1
            
            volume_increasing = False
            if len(hist) >= 20:
                vol_recent = hist['Volume'].iloc[-5:].mean()
                vol_past = hist['Volume'].iloc[-20:-5].mean()
                volume_increasing = vol_recent > vol_past if vol_past > 0 else False
            
            if volume_increasing:
                bullish_signals += 1
            total_signals += 1
            
            base_confidence = (bullish_signals / total_signals) * 100
            
            if current_price <= entry_point and rsi < 35 and macd > macd_signal and adx > 25:
                investment_timing = "BUY NOW"
                timing_reason = "Strong oversold bounce setup with bullish MACD & strong trend"
                risk_level = "LOW"
                confidence_score = min(base_confidence + 15, 95)
                
            elif current_price <= entry_point * 1.05 and rsi < 40 and current_price > sma_20 and sma_20 > sma_50:
                investment_timing = "BUY NOW"
                timing_reason = "Perfect entry - Price above SMA20>SMA50, healthy RSI, near support"
                risk_level = "LOW"
                confidence_score = min(base_confidence + 12, 92)
                
            elif current_price > sma_20 and sma_20 > sma_50 and current_price > sma_200 and rsi < 55 and adx > 25:
                investment_timing = "BUY NOW"
                timing_reason = "Confirmed uptrend - All SMAs aligned, strong momentum, healthy RSI"
                risk_level = "LOW-MEDIUM"
                confidence_score = min(base_confidence + 10, 90)
                
            elif macd > macd_signal and macd_hist > 0 and rsi < 50 and current_price > sma_20:
                investment_timing = "ACCUMULATE"
                timing_reason = "Bullish MACD crossover with uptrend - Buy in parts"
                risk_level = "MEDIUM"
                confidence_score = min(base_confidence + 8, 85)
                
            elif current_price < entry_point * 1.15 and rsi < 50 and current_price > bb_lower:
                investment_timing = "BUY ON DIP"
                timing_reason = "Near entry zone - Wait for small pullback to support"
                risk_level = "MEDIUM"
                confidence_score = min(base_confidence + 5, 80)
                
            elif rsi > 70 or current_price > bb_upper:
                investment_timing = "WAIT"
                timing_reason = "Overbought - High risk of correction"
                risk_level = "HIGH"
                confidence_score = max(base_confidence - 15, 30)
                
            elif current_price > resistance * 0.95:
                investment_timing = "WAIT"
                timing_reason = "Near resistance - Risk of rejection"
                risk_level = "HIGH"
                confidence_score = max(base_confidence - 10, 35)
                
            elif current_price < sma_20 < sma_50:
                investment_timing = "WAIT"
                timing_reason = "Downtrend - Wait for trend reversal"
                risk_level = "HIGH"
                confidence_score = max(base_confidence - 20, 25)
                
            else:
                investment_timing = "MONITOR"
                timing_reason = "Mixed signals - Track for clearer entry opportunity"
                risk_level = "MEDIUM"
                confidence_score = base_confidence
            
            potential_gain = ((profit_target_1 - current_price) / current_price) * 100
            potential_loss = ((current_price - stop_loss) / current_price) * 100
            
            return {
                'entry_point': float(entry_point),
                'current_price': float(current_price),
                'stop_loss': float(stop_loss),
                'target_1': float(profit_target_1),
                'target_2': float(profit_target_2),
                'support': float(support),
                'resistance': float(resistance),
                'rsi': float(rsi),
                'macd': float(macd),
                'macd_signal': float(macd_signal),
                'macd_histogram': float(macd_hist),
                'adx': float(adx),
                'bb_upper': float(bb_upper),
                'bb_lower': float(bb_lower),
                'sma_20': float(sma_20),
                'sma_50': float(sma_50),
                'investment_timing': investment_timing,
                'timing_reason': timing_reason,
                'risk_level': risk_level,
                'confidence_score': round(confidence_score, 1),
                'bullish_signals': f"{bullish_signals}/{total_signals}",
                'potential_gain': float(potential_gain),
                'potential_loss': float(potential_loss),
                'distance_to_52w_high': float(((high_52w - current_price) / current_price) * 100),
                'fib_levels': fib_levels
            }
        except Exception as e:
            return None
    
    def calculate_investment_allocation(self, stock, rank, total_stocks):
        try:
            signals = stock['signals']
            risk_level = signals['risk_level']
            
            risk_weights = {
                'LOW': 0.18,
                'LOW-MEDIUM': 0.15,
                'MEDIUM': 0.12,
                'MEDIUM-HIGH': 0.08,
                'HIGH': 0.05
            }
            
            base_allocation = risk_weights.get(risk_level, 0.10)
            
            confidence_boost = max((signals['confidence_score'] - 80) / 100, 0)
            base_allocation = base_allocation * (1 + confidence_boost)
            
            rank_factor = 1 - ((rank - 1) * 0.04)
            rank_factor = max(rank_factor, 0.6)
            
            final_allocation = base_allocation * rank_factor
            
            investment_amount = self.investment_capital * final_allocation
            
            current_price = stock['current_price']
            if current_price <= 0:
                return None
            
            shares_to_buy = max(int(investment_amount / current_price), 1)
            actual_investment = shares_to_buy * current_price
            
            if actual_investment <= 0:
                return None
            
            expected_return = actual_investment * (signals['potential_gain'] / 100)
            exit_value = actual_investment + expected_return
            roi_percentage = (expected_return / actual_investment) * 100
            
            return {
                'allocation_percentage': float(final_allocation * 100),
                'investment_amount': float(actual_investment),
                'shares_to_buy': int(shares_to_buy),
                'expected_return': float(expected_return),
                'exit_value': float(exit_value),
                'roi_percentage': float(roi_percentage)
            }
        except:
            return None
    
    def analyze_stocks(self):
        print(f"\nAnalyzing {len(self.stock_data)} stocks for high-confidence opportunities...")
        print(f"Minimum confidence threshold: {self.min_confidence}%")
        print("=" * 80)
        
        for symbol, data in self.stock_data.items():
            try:
                hist = data['history']
                signals = self.generate_investment_signals(hist, data['current_price'])
                
                if signals is None:
                    continue
                
                close_prices = hist['Close']
                
                price_change_1w = 0
                price_change_1m = 0
                
                if len(close_prices) >= 5:
                    price_change_1w = ((close_prices.iloc[-1] - close_prices.iloc[-5]) / close_prices.iloc[-5]) * 100
                
                if len(close_prices) >= 20:
                    price_change_1m = ((close_prices.iloc[-1] - close_prices.iloc[-20]) / close_prices.iloc[-20]) * 100
                
                momentum = self.calculate_momentum_score(hist)
                quality_score = (signals['confidence_score'] * 0.7) + (momentum * 0.3)
                
                dates = self.predict_entry_exit_dates(hist, data['current_price'], signals)
                
                self.analyzed_stocks.append({
                    'symbol': symbol,
                    'name': data['name'],
                    'current_price': data['current_price'],
                    'change_1w': float(price_change_1w),
                    'change_1m': float(price_change_1m),
                    'quality_score': float(quality_score),
                    'history': hist,
                    'signals': signals,
                    'dates': dates
                })
            except Exception as e:
                continue
        
        if not self.analyzed_stocks:
            print("\n⚠️  Failed to analyze any stocks. Please check your internet connection.")
            self.top_stocks = []
            return
        
        self.analyzed_stocks.sort(key=lambda x: x['signals']['confidence_score'], reverse=True)
        
        high_confidence_stocks = [
            s for s in self.analyzed_stocks 
            if s['signals']['confidence_score'] >= self.min_confidence
            and s['signals']['investment_timing'] in ['BUY NOW', 'BUY ON DIP', 'ACCUMULATE']
        ]
        
        print(f"\n{'='*80}")
        print(f"ANALYSIS RESULTS:")
        print(f"{'='*80}")
        print(f"Total stocks analyzed: {len(self.analyzed_stocks)}")
        print(f"Stocks with {self.min_confidence}%+ confidence: {len(high_confidence_stocks)}")
        
        if not high_confidence_stocks:
            print(f"\n⚠️  NO STOCKS found with confidence >= {self.min_confidence}%")
            self.top_stocks = []
            return
        
        valid_stocks = []
        for i, stock in enumerate(high_confidence_stocks, 1):
            allocation = self.calculate_investment_allocation(stock, i, len(high_confidence_stocks))
            
            if allocation is None or allocation['investment_amount'] <= 0:
                continue
            
            stock['allocation'] = allocation
            valid_stocks.append(stock)
        
        self.top_stocks = valid_stocks
        print(f"Valid investment opportunities: {len(self.top_stocks)}")
    
    def create_individual_stock_chart(self, stock, rank):
        try:
            fig = plt.figure(figsize=(16, 10))
            fig.patch.set_facecolor('#F5F5F5')
            
            hist = stock['history']
            signals = stock['signals']
            allocation = stock['allocation']
            dates = stock['dates']
            
            gs = fig.add_gridspec(3, 2, height_ratios=[2, 1, 1], hspace=0.3, wspace=0.3)
            
            ax_price = fig.add_subplot(gs[0, :])
            ax_price.plot(hist.index, hist['Close'], color='#00A3E0', linewidth=3, label='Price', zorder=5)
            
            sma_20 = hist['Close'].rolling(window=20).mean()
            ax_price.plot(hist.index, sma_20, color='#86BC25', linewidth=2, 
                         linestyle='--', label='SMA 20', alpha=0.8)
            
            if len(hist) >= 50:
                sma_50 = hist['Close'].rolling(window=50).mean()
                ax_price.plot(hist.index, sma_50, color='#FF9800', linewidth=2, 
                             linestyle='--', label='SMA 50', alpha=0.8)
            
            ax_price.axhline(y=signals['entry_point'], color='#00CC88', linestyle='-.', 
                            linewidth=2.5, label='Entry Point', alpha=0.9, zorder=4)
            ax_price.axhline(y=signals['target_1'], color='#4CAF50', linestyle=':', 
                            linewidth=2.5, label='Target 1', alpha=0.9, zorder=4)
            ax_price.axhline(y=signals['stop_loss'], color='#FF4444', linestyle=':', 
                            linewidth=2.5, label='Stop Loss', alpha=0.9, zorder=4)
            
            ax_price.fill_between(hist.index, signals['support'], signals['resistance'], 
                                 alpha=0.1, color='#86BC25', label='Support-Resistance Zone')
            
            ax_price.set_title(f"#{rank}. {stock['name']} ({stock['symbol'].replace('.NS', '')})\n"
                              f"Investment Plan - Confidence: {signals['confidence_score']}%",
                              fontsize=16, fontweight='bold', pad=15)
            ax_price.set_ylabel('Price (₹)', fontsize=12, fontweight='bold')
            ax_price.legend(loc='upper left', fontsize=10, framealpha=0.95)
            ax_price.grid(True, alpha=0.3, linestyle=':')
            ax_price.set_facecolor('#FFFFFF')
            
            ax_volume = fig.add_subplot(gs[1, :], sharex=ax_price)
            colors = ['#00CC88' if hist['Close'].iloc[i] >= hist['Open'].iloc[i] else '#FF4444' 
                     for i in range(len(hist))]
            ax_volume.bar(hist.index, hist['Volume'], color=colors, alpha=0.6, width=0.8)
            ax_volume.set_ylabel('Volume', fontsize=10, fontweight='bold')
            ax_volume.grid(True, alpha=0.2, linestyle=':')
            ax_volume.set_facecolor('#FFFFFF')
            
            ax_info = fig.add_subplot(gs[2, 0])
            ax_info.axis('off')
            
            info_text = f"📊 CURRENT STATUS\n"
            info_text += f"{'='*35}\n"
            info_text += f"Current Price: ₹{stock['current_price']:.2f}\n"
            info_text += f"1 Week Change: {stock['change_1w']:+.2f}%\n"
            info_text += f"1 Month Change: {stock['change_1m']:+.2f}%\n\n"
            info_text += f"📈 TECHNICAL INDICATORS\n"
            info_text += f"{'='*35}\n"
            info_text += f"RSI: {signals['rsi']:.1f}\n"
            info_text += f"MACD: {signals['macd']:.2f}\n"
            info_text += f"ADX: {signals['adx']:.1f}\n"
            info_text += f"Bullish Signals: {signals['bullish_signals']}\n\n"
            info_text += f"💰 RECOMMENDATION\n"
            info_text += f"{'='*35}\n"
            info_text += f"Action: {signals['investment_timing']}\n"
            info_text += f"Risk Level: {signals['risk_level']}\n"
            info_text += f"Confidence: {signals['confidence_score']}%"
            
            ax_info.text(0.05, 0.95, info_text, transform=ax_info.transAxes,
                        fontsize=9, verticalalignment='top', fontfamily='monospace',
                        bbox=dict(boxstyle='round', facecolor='#E8F5E9', 
                                edgecolor='#86BC25', linewidth=2, pad=15))
            
            ax_plan = fig.add_subplot(gs[2, 1])
            ax_plan.axis('off')
            
            plan_text = f"📅 INVESTMENT PLAN\n"
            plan_text += f"{'='*35}\n"
            plan_text += f"Buy Date: {dates['entry_date'].strftime('%d %b %Y')}\n"
            plan_text += f"Exit Date: {dates['exit_date'].strftime('%d %b %Y')}\n"
            plan_text += f"Hold: {dates['holding_days']} days\n\n"
            plan_text += f"💵 INVESTMENT DETAILS\n"
            plan_text += f"{'='*35}\n"
            plan_text += f"Invest: ₹{allocation['investment_amount']:,.0f}\n"
            plan_text += f"Shares: {allocation['shares_to_buy']}\n"
            plan_text += f"Entry: ₹{signals['entry_point']:.2f}\n"
            plan_text += f"Target: ₹{signals['target_1']:.2f}\n"
            plan_text += f"Stop Loss: ₹{signals['stop_loss']:.2f}\n\n"
            plan_text += f"📈 EXPECTED RETURNS\n"
            plan_text += f"{'='*35}\n"
            plan_text += f"Profit: ₹{allocation['expected_return']:,.0f}\n"
            plan_text += f"ROI: {allocation['roi_percentage']:.1f}%\n"
            plan_text += f"Exit Value: ₹{allocation['exit_value']:,.0f}"
            
            ax_plan.text(0.05, 0.95, plan_text, transform=ax_plan.transAxes,
                        fontsize=9, verticalalignment='top', fontfamily='monospace',
                        bbox=dict(boxstyle='round', facecolor='#FFF3E0', 
                                edgecolor='#FF9800', linewidth=2, pad=15))
            
            disclaimer = "⚠️ DISCLAIMER: This is educational analysis only. Not financial advice. Past performance ≠ future results."
            fig.text(0.5, 0.02, disclaimer, ha='center', fontsize=8, style='italic', color='#666666')
            
            filename = os.path.join(self.output_folder, 
                                   f"{rank:02d}_{stock['symbol'].replace('.NS', '')}_investment_plan.png")
            plt.savefig(filename, dpi=300, bbox_inches='tight', facecolor='#F5F5F5')
            plt.close()
            
            return filename
        except Exception as e:
            print(f"Error creating chart for {stock['name']}: {str(e)}")
            return None
    
    def create_excel_report(self):
        if not OPENPYXL_AVAILABLE:
            print("⚠️  Excel formatting not available. Creating basic CSV...")
            self.save_basic_csv()
            return
        
        if not self.top_stocks:
            print("⚠️  No stocks to save")
            return
        
        try:
            filename = os.path.join(self.output_folder, 
                                   f'Investment_Report_{self.today.strftime("%Y%m%d_%H%M")}.xlsx')
            
            wb = Workbook()
            
            ws_summary = wb.active
            ws_summary.title = "Portfolio Summary"
            
            ws_summary['A1'] = "HIGH CONFIDENCE STOCK INVESTMENT REPORT"
            ws_summary['A1'].font = Font(size=16, bold=True, color='FFFFFF')
            ws_summary['A1'].fill = PatternFill(start_color='86BC25', end_color='86BC25', fill_type='solid')
            ws_summary['A1'].alignment = Alignment(horizontal='center', vertical='center')
            ws_summary.merge_cells('A1:F1')
            ws_summary.row_dimensions[1].height = 30
            
            ws_summary['A3'] = f"Analysis Date: {self.today.strftime('%d %B %Y, %I:%M %p IST')}"
            ws_summary['A3'].font = Font(size=11, italic=True)
            ws_summary.merge_cells('A3:F3')
            
            total_investment = sum(s['allocation']['investment_amount'] for s in self.top_stocks)
            total_return = sum(s['allocation']['expected_return'] for s in self.top_stocks)
            avg_roi = (total_return / total_investment * 100) if total_investment > 0 else 0
            avg_confidence = sum(s['signals']['confidence_score'] for s in self.top_stocks) / len(self.top_stocks)
            avg_holding = sum(s['dates']['holding_days'] for s in self.top_stocks) / len(self.top_stocks)
            
            summary_data = [
                ['Total Investment Capital', f"₹{self.investment_capital:,.2f}"],
                ['Amount to Invest', f"₹{total_investment:,.2f}"],
                ['Expected Returns', f"₹{total_return:,.2f}"],
                ['Total Exit Value', f"₹{total_investment + total_return:,.2f}"],
                ['Portfolio ROI', f"{avg_roi:.2f}%"],
                ['Number of Stocks', len(self.top_stocks)],
                ['Average Confidence', f"{avg_confidence:.1f}%"],
                ['Average Holding Period', f"{avg_holding:.0f} days"],
                ['Minimum Confidence Threshold', f"{self.min_confidence}%"]
            ]
            
            start_row = 5
            for i, (label, value) in enumerate(summary_data, start=start_row):
                ws_summary[f'A{i}'] = label
                ws_summary[f'A{i}'].font = Font(bold=True)
                ws_summary[f'B{i}'] = value
                ws_summary[f'B{i}'].font = Font(size=11)
            
            for row in range(start_row, start_row + len(summary_data)):
                ws_summary[f'A{row}'].fill = PatternFill(start_color='E8F5E9', end_color='E8F5E9', fill_type='solid')
                ws_summary[f'B{row}'].fill = PatternFill(start_color='FFFFFF', end_color='FFFFFF', fill_type='solid')
            
            ws_summary.column_dimensions['A'].width = 30
            ws_summary.column_dimensions['B'].width = 25
            
            ws_details = wb.create_sheet(title="Investment Details")
            
            headers = ['Rank', 'Company Name', 'Symbol', 'Current Price', 'Confidence %', 
                      'Action', 'Risk Level', 'Buy Date', 'Exit Date', 'Hold Days',
                      'Invest Amount', 'Shares', 'Entry Price', 'Target Price', 'Stop Loss',
                      'Expected Return', 'ROI %', 'RSI', 'MACD', 'ADX', 'Reason']
            
            for col, header in enumerate(headers, start=1):
                cell = ws_details.cell(row=1, column=col, value=header)
                cell.font = Font(bold=True, color='FFFFFF', size=11)
                cell.fill = PatternFill(start_color='00A3E0', end_color='00A3E0', fill_type='solid')
                cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
            
            for idx, stock in enumerate(self.top_stocks, start=2):
                signals = stock['signals']
                allocation = stock['allocation']
                dates = stock['dates']
                
                row_data = [
                    idx - 1,
                    stock['name'],
                    stock['symbol'].replace('.NS', ''),
                    f"₹{stock['current_price']:.2f}",
                    f"{signals['confidence_score']:.1f}%",
                    signals['investment_timing'],
                    signals['risk_level'],
                    dates['entry_date'].strftime('%d-%b-%Y'),
                    dates['exit_date'].strftime('%d-%b-%Y'),
                    dates['holding_days'],
                    f"₹{allocation['investment_amount']:,.2f}",
                    allocation['shares_to_buy'],
                    f"₹{signals['entry_point']:.2f}",
                    f"₹{signals['target_1']:.2f}",
                    f"₹{signals['stop_loss']:.2f}",
                    f"₹{allocation['expected_return']:,.2f}",
                    f"{allocation['roi_percentage']:.2f}%",
                    f"{signals['rsi']:.1f}",
                    f"{signals['macd']:.2f}",
                    f"{signals['adx']:.1f}",
                    signals['timing_reason']
                ]
                
                for col, value in enumerate(row_data, start=1):
                    cell = ws_details.cell(row=idx, column=col, value=value)
                    cell.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
                    
                    if idx % 2 == 0:
                        cell.fill = PatternFill(start_color='F5F5F5', end_color='F5F5F5', fill_type='solid')
                    
                    if col == 5:
                        conf = signals['confidence_score']
                        if conf >= 85:
                            cell.fill = PatternFill(start_color='C8E6C9', end_color='C8E6C9', fill_type='solid')
                        elif conf >= 80:
                            cell.fill = PatternFill(start_color='FFF9C4', end_color='FFF9C4', fill_type='solid')
                    
                    if col == 6:
                        if value == 'BUY NOW':
                            cell.fill = PatternFill(start_color='A5D6A7', end_color='A5D6A7', fill_type='solid')
                            cell.font = Font(bold=True, color='1B5E20')
            
            for col in range(1, len(headers) + 1):
                ws_details.column_dimensions[ws_details.cell(row=1, column=col).column_letter].width = 15
            
            ws_details.column_dimensions['B'].width = 30
            ws_details.column_dimensions['U'].width = 40
            
            ws_dates = wb.create_sheet(title="Investment Calendar")
            
            ws_dates['A1'] = "INVESTMENT CALENDAR - ACTION DATES"
            ws_dates['A1'].font = Font(size=14, bold=True, color='FFFFFF')
            ws_dates['A1'].fill = PatternFill(start_color='FF9800', end_color='FF9800', fill_type='solid')
            ws_dates['A1'].alignment = Alignment(horizontal='center', vertical='center')
            ws_dates.merge_cells('A1:F1')
            ws_dates.row_dimensions[1].height = 25
            
            cal_headers = ['Rank', 'Stock', 'Action', 'Buy Date', 'Stop-Loss Review', 'Exit Date']
            for col, header in enumerate(cal_headers, start=1):
                cell = ws_dates.cell(row=3, column=col, value=header)
                cell.font = Font(bold=True, size=11)
                cell.fill = PatternFill(start_color='FFE0B2', end_color='FFE0B2', fill_type='solid')
                cell.alignment = Alignment(horizontal='center', vertical='center')
            
            sorted_stocks = sorted(self.top_stocks, key=lambda x: x['dates']['entry_date'])
            
            for idx, stock in enumerate(sorted_stocks, start=4):
                dates = stock['dates']
                signals = stock['signals']
                
                ws_dates[f'A{idx}'] = idx - 3
                ws_dates[f'B{idx}'] = stock['symbol'].replace('.NS', '')
                ws_dates[f'C{idx}'] = signals['investment_timing']
                ws_dates[f'D{idx}'] = dates['entry_date'].strftime('%d %B %Y (%A)')
                ws_dates[f'E{idx}'] = dates['stop_loss_check_date'].strftime('%d %B %Y')
                ws_dates[f'F{idx}'] = dates['exit_date'].strftime('%d %B %Y (%A)')
                
                for col in range(1, 7):
                    ws_dates.cell(row=idx, column=col).alignment = Alignment(horizontal='left', vertical='center')
                    if idx % 2 == 0:
                        ws_dates.cell(row=idx, column=col).fill = PatternFill(start_color='FFF8E1', 
                                                                               end_color='FFF8E1', fill_type='solid')
            
            ws_dates.column_dimensions['A'].width = 8
            ws_dates.column_dimensions['B'].width = 20
            ws_dates.column_dimensions['C'].width = 15
            ws_dates.column_dimensions['D'].width = 30
            ws_dates.column_dimensions['E'].width = 20
            ws_dates.column_dimensions['F'].width = 30
            
            wb.save(filename)
            print(f"\n✓ Professional Excel report saved: '{filename}'")
            return filename
            
        except Exception as e:
            print(f"✗ Error creating Excel: {str(e)}")
            return None
    
    def save_basic_csv(self):
        try:
            filename = os.path.join(self.output_folder, 
                                   f'investment_plan_{self.today.strftime("%Y%m%d_%H%M")}.csv')
            
            plan_data = []
            for stock in self.top_stocks:
                signals = stock['signals']
                allocation = stock['allocation']
                dates = stock['dates']
                
                plan_data.append({
                    'Rank': self.top_stocks.index(stock) + 1,
                    'Stock': stock['name'],
                    'Symbol': stock['symbol'].replace('.NS', ''),
                    'Confidence %': signals['confidence_score'],
                    'Current Price': f"₹{stock['current_price']:.2f}",
                    'Investment Action': signals['investment_timing'],
                    'Risk Level': signals['risk_level'],
                    'Buy Date': dates['entry_date'].strftime('%d-%b-%Y'),
                    'Exit Date': dates['exit_date'].strftime('%d-%b-%Y'),
                    'Holding Days': dates['holding_days'],
                    'Invest Amount': f"₹{allocation['investment_amount']:,.2f}",
                    'Shares': allocation['shares_to_buy'],
                    'Entry Price': f"₹{signals['entry_point']:.2f}",
                    'Stop Loss': f"₹{signals['stop_loss']:.2f}",
                    'Target': f"₹{signals['target_1']:.2f}",
                    'Expected Return': f"₹{allocation['expected_return']:,.2f}",
                    'ROI %': f"{allocation['roi_percentage']:.2f}%"
                })
            
            df = pd.DataFrame(plan_data)
            df.to_csv(filename, index=False)
            print(f"✓ CSV report saved: '{filename}'")
        except Exception as e:
            print(f"✗ Error saving CSV: {str(e)}")
    
    def generate_all_reports(self):
        if not self.top_stocks:
            print("\n⚠️  No high-confidence stocks found. No reports to generate.")
            return
        
        print(f"\n\n{'='*80}")
        print(f"GENERATING INDIVIDUAL STOCK INVESTMENT PLANS")
        print(f"{'='*80}\n")
        
        for idx, stock in enumerate(self.top_stocks, 1):
            print(f"Creating investment card {idx}/{len(self.top_stocks)}: {stock['name']}...", end=' ')
            chart_file = self.create_individual_stock_chart(stock, idx)
            if chart_file:
                print("✓")
            else:
                print("✗")
        
        print(f"\n{'='*80}")
        print(f"GENERATING EXCEL REPORT")
        print(f"{'='*80}\n")
        
        excel_file = self.create_excel_report()
        
        print(f"\n{'='*80}")
        print(f"ALL REPORTS GENERATED SUCCESSFULLY!")
        print(f"{'='*80}")
        print(f"\n📁 Output Folder: {self.output_folder}")
        print(f"   • Individual Investment Plans: {len(self.top_stocks)} PNG files")
        print(f"   • Excel Report: 1 XLSX file with 3 sheets")
        print(f"\nOpen the folder to view all investment plans and charts!")

def main():
    print("\n" + "="*80)
    print("   🎯 HIGH CONFIDENCE INDIAN STOCK INVESTMENT ADVISOR")
    print("   Complete Reports with Individual Stock Charts & Excel Analysis")
    print("="*80 + "\n")
    
    try:
        capital = input("Enter investment capital (default ₹100,000): ").strip()
        if capital and capital.replace(',', '').replace('.', '').isdigit():
            capital = float(capital.replace(',', ''))
        else:
            capital = 100000
        
        min_conf = input("Enter minimum confidence % (default 80): ").strip()
        if min_conf and min_conf.isdigit():
            min_conf = int(min_conf)
        else:
            min_conf = 80
        
        print(f"\n✓ Investment Capital: ₹{capital:,.2f}")
        print(f"✓ Minimum Confidence: {min_conf}%")
        print(f"\nStarting analysis of 100+ NSE stocks...")
        print("This may take 2-3 minutes for comprehensive analysis...")
        
        advisor = HighConfidenceStockAdvisor(investment_capital=capital, min_confidence=min_conf)
        
        print(f"\n📂 Output folder created: {advisor.output_folder}")
        
        advisor.fetch_latest_stock_data()
        
        if not advisor.stock_data:
            print("\n✗ Failed to fetch stock data. Please check your internet connection.")
            return
        
        advisor.analyze_stocks()
        
        if not advisor.top_stocks:
            print("\n💡 TIP: Try lowering the confidence threshold (e.g., 70%) to see more opportunities.")
            print("\nWould you like to try with lower confidence? (y/n): ", end='')
            retry = input().strip().lower()
            if retry == 'y':
                new_conf = input("Enter new confidence threshold (e.g., 70): ").strip()
                if new_conf.isdigit():
                    advisor.min_confidence = int(new_conf)
                    advisor.analyze_stocks()
        
        if advisor.top_stocks:
            print(f"\n✓ Found {len(advisor.top_stocks)} high-confidence investment opportunities!")
            
            total_invested = sum(s['allocation']['investment_amount'] for s in advisor.top_stocks)
            total_return = sum(s['allocation']['expected_return'] for s in advisor.top_stocks)
            
            print(f"\n{'='*80}")
            print(f"PORTFOLIO SUMMARY")
            print(f"{'='*80}")
            print(f"Total Investment: ₹{total_invested:,.2f}")
            print(f"Expected Returns: ₹{total_return:,.2f}")
            print(f"Portfolio ROI: {(total_return/total_invested)*100:.2f}%")
            print(f"Number of Stocks: {len(advisor.top_stocks)}")
            
            print("\nTop 5 Recommendations:")
            for i, stock in enumerate(advisor.top_stocks[:5], 1):
                print(f"{i}. {stock['name']}: {stock['signals']['investment_timing']} "
                      f"(Confidence: {stock['signals']['confidence_score']}%)")
            
            generate = input("\nGenerate detailed reports (Excel + individual charts)? (y/n): ").strip().lower()
            if generate == 'y':
                advisor.generate_all_reports()
                
                print("\n" + "="*80)
                print("✅ REPORT GENERATION COMPLETE!")
                print("="*80)
                print(f"\n📂 All files saved in: {advisor.output_folder}")
                print("\n📊 What's included:")
                print(f"   ✓ {len(advisor.top_stocks)} individual stock investment cards (PNG)")
                print(f"   ✓ 1 comprehensive Excel report with:")
                print(f"     • Portfolio Summary sheet")
                print(f"     • Detailed Investment Analysis sheet")
                print(f"     • Investment Calendar sheet")
                print("\n💡 Next Steps:")
                print("   1. Open the Excel file for detailed analysis")
                print("   2. Review individual stock charts for each opportunity")
                print("   3. Set calendar reminders for buy/sell dates")
                print("   4. Monitor stocks according to the action plan")
                
                import platform
                if platform.system() == 'Windows':
                    print(f"\n📂 Opening folder...")
                    os.startfile(advisor.output_folder)
                elif platform.system() == 'Darwin':  # macOS
                    os.system(f'open "{advisor.output_folder}"')
                else:  # Linux
                    os.system(f'xdg-open "{advisor.output_folder}"')
            else:
                print("\n✓ Analysis complete. Reports not generated.")
        
        print("\n" + "="*80)
        print("⚠️  CRITICAL DISCLAIMER:")
        print("="*80)
        print("This is EDUCATIONAL ANALYSIS ONLY, not financial advice.")
        print("Confidence scores are based on technical indicators and historical data.")
        print("Past performance does NOT guarantee future results.")
        print("\n🚨 BEFORE INVESTING:")
        print("1. Consult a SEBI-registered financial advisor")
        print("2. Understand your risk tolerance and investment goals")
        print("3. Never invest money you cannot afford to lose")
        print("4. Diversify across asset classes, not just stocks")
        print("5. Conduct your own research (DYOR)")
        print("6. Markets are unpredictable - manage risk with stop-losses")
        print("7. Review and validate all recommendations independently")
        print("="*80 + "\n")
    
    except KeyboardInterrupt:
        print("\n\n⚠️  Analysis interrupted by user")
    except Exception as e:
        print(f"\n✗ An error occurred: {str(e)}")
        print("Please try again or check your internet connection.")

if __name__ == '__main__':
    main()