# filename: india_stock_advisor_fixed.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import numpy as np
import warnings
import time
import os
warnings.filterwarnings('ignore')

class HighConfidenceStockAdvisor:
    def __init__(self, investment_capital=100000, min_confidence=80):
        self.nse_stocks = [
            'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
            'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
            'LT.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'MARUTI.NS', 'TITAN.NS',
            'SUNPHARMA.NS', 'ULTRACEMCO.NS', 'NESTLEIND.NS', 'BAJFINANCE.NS', 'WIPRO.NS',
            'HCLTECH.NS', 'TECHM.NS', 'POWERGRID.NS', 'NTPC.NS', 'ONGC.NS',
            'TATASTEEL.NS', 'ADANIENT.NS', 'JSWSTEEL.NS', 'GRASIM.NS', 'HINDALCO.NS',
            'DIVISLAB.NS', 'DRREDDY.NS', 'CIPLA.NS', 'EICHERMOT.NS', 'HEROMOTOCO.NS',
            'M&M.NS', 'BAJAJFINSV.NS', 'TATACONSUM.NS', 'INDUSINDBK.NS', 'COALINDIA.NS',
            'BRITANNIA.NS', 'APOLLOHOSP.NS', 'PIDILITIND.NS', 'DABUR.NS', 'GODREJCP.NS',
            'ADANIPORTS.NS', 'SHREECEM.NS', 'BPCL.NS', 'IOC.NS', 'VEDL.NS',
            'TORNTPHARM.NS', 'LUPIN.NS', 'BIOCON.NS', 'BAJAJ-AUTO.NS', 'HAVELLS.NS',
            'SIEMENS.NS', 'DLF.NS', 'GAIL.NS', 'AMBUJACEM.NS', 'ACC.NS',
            'TATAPOWER.NS', 'ADANIGREEN.NS', 'BANDHANBNK.NS', 'INDUSTOWER.NS', 'PNB.NS',
            'SAIL.NS', 'NMDC.NS', 'RECLTD.NS', 'IDEA.NS', 'ZEEL.NS',
            'MOTHERSON.NS', 'BALKRISIND.NS', 'BOSCHLTD.NS', 'ABCAPITAL.NS', 'MPHASIS.NS',
            'BERGEPAINT.NS', 'PAGEIND.NS', 'COLPAL.NS', 'MARICO.NS', 'PERSISTENT.NS',
            'MCDOWELL-N.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'ICICIPRULI.NS', 'BAJAJHLDNG.NS',
            'SBICARD.NS', 'TRENT.NS', 'ZOMATO.NS', 'NYKAA.NS', 'PAYTM.NS',
            'DMART.NS', 'IRCTC.NS', 'PGHH.NS', 'INDIGO.NS', 'VOLTAS.NS',
            'CUMMINSIND.NS', 'COFORGE.NS', 'LTIM.NS', 'TATAELXSI.NS', 
            'CROMPTON.NS', 'JUBLFOOD.NS', 'GODREJPROP.NS', 'OBEROIRLTY.NS', 'PRESTIGE.NS'
        ]
        
        self.investment_capital = max(investment_capital, 1000)
        self.min_confidence = max(min(min_confidence, 100), 50)
        self.stock_data = {}
        self.analyzed_stocks = []
        self.today = datetime.now()
        
    def fetch_latest_stock_data(self):
        print(f"Fetching LATEST data from {len(self.nse_stocks)} NSE stocks...")
        print(f"Data retrieval time: {self.today.strftime('%Y-%m-%d %H:%M:%S IST')}")
        print("=" * 80)
        
        successful = 0
        failed = 0
        
        for idx, symbol in enumerate(self.nse_stocks, 1):
            try:
                print(f"[{idx}/{len(self.nse_stocks)}] {symbol}...", end=' ')
                
                stock = yf.Ticker(symbol)
                hist_6m = stock.history(period='6mo')
                
                if hist_6m.empty or len(hist_6m) < 30:
                    print(f"✗ Insufficient data")
                    failed += 1
                    continue
                
                try:
                    hist_1d = stock.history(period='1d', interval='1m')
                except:
                    hist_1d = pd.DataFrame()
                
                try:
                    info = stock.info
                    company_name = info.get('longName', symbol.replace('.NS', ''))
                except:
                    company_name = symbol.replace('.NS', '')
                
                current_price = hist_6m['Close'].iloc[-1]
                
                if not hist_1d.empty and len(hist_1d) > 0:
                    try:
                        current_price = hist_1d['Close'].iloc[-1]
                    except:
                        pass
                
                if pd.isna(current_price) or current_price <= 0:
                    print(f"✗ Invalid price")
                    failed += 1
                    continue
                
                self.stock_data[symbol] = {
                    'history': hist_6m,
                    'intraday': hist_1d,
                    'name': company_name,
                    'current_price': float(current_price),
                    'symbol': symbol,
                    'last_update': self.today
                }
                print(f"✓ ₹{current_price:.2f}")
                successful += 1
                
                if idx % 10 == 0:
                    time.sleep(1)
                
            except Exception as e:
                print(f"✗ Error")
                failed += 1
        
        print(f"\n{'='*80}")
        print(f"✓ Successfully loaded: {successful} stocks")
        print(f"✗ Failed to load: {failed} stocks")
        print(f"Total stocks for analysis: {len(self.stock_data)}")
        print(f"{'='*80}")
    
    def safe_calculate(self, func, default=0):
        try:
            result = func()
            if pd.isna(result) or np.isinf(result):
                return default
            return result
        except:
            return default
    
    def calculate_fibonacci_levels(self, hist):
        try:
            high = hist['High'].max()
            low = hist['Low'].min()
            diff = high - low
            
            if diff <= 0:
                return None
            
            return {
                'level_0': low,
                'level_23.6': low + (diff * 0.236),
                'level_38.2': low + (diff * 0.382),
                'level_50': low + (diff * 0.5),
                'level_61.8': low + (diff * 0.618),
                'level_78.6': low + (diff * 0.786),
                'level_100': high
            }
        except:
            return None
    
    def calculate_bollinger_bands(self, prices, period=20):
        try:
            if len(prices) < period:
                return None, None, None
            
            sma = prices.rolling(window=period).mean()
            std = prices.rolling(window=period).std()
            
            if pd.isna(sma.iloc[-1]) or pd.isna(std.iloc[-1]):
                return None, None, None
            
            upper_band = sma + (std * 2)
            lower_band = sma - (std * 2)
            
            return float(upper_band.iloc[-1]), float(sma.iloc[-1]), float(lower_band.iloc[-1])
        except:
            return None, None, None
    
    def calculate_momentum_score(self, hist):
        try:
            close = hist['Close']
            
            if len(close) < 20:
                return 0
            
            roc_5 = ((close.iloc[-1] - close.iloc[-5]) / close.iloc[-5]) * 100 if len(close) >= 5 else 0
            roc_10 = ((close.iloc[-1] - close.iloc[-10]) / close.iloc[-10]) * 100 if len(close) >= 10 else 0
            roc_20 = ((close.iloc[-1] - close.iloc[-20]) / close.iloc[-20]) * 100 if len(close) >= 20 else 0
            
            if len(hist) >= 20:
                vol_recent = hist['Volume'].iloc[-5:].mean()
                vol_past = hist['Volume'].iloc[-20:-5].mean()
                volume_ratio = vol_recent / vol_past if vol_past > 0 else 1
            else:
                volume_ratio = 1
            
            momentum = (roc_5 * 0.5) + (roc_10 * 0.3) + (roc_20 * 0.2) + (volume_ratio * 10)
            
            if pd.isna(momentum) or np.isinf(momentum):
                return 0
            
            return float(momentum)
        except:
            return 0
    
    def calculate_rsi(self, prices, period=14):
        try:
            if len(prices) < period + 1:
                return 50
            
            delta = prices.diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
            
            if loss.iloc[-1] == 0:
                return 100 if gain.iloc[-1] > 0 else 50
            
            rs = gain / loss
            rsi = 100 - (100 / (1 + rs))
            
            result = rsi.iloc[-1]
            if pd.isna(result) or np.isinf(result):
                return 50
            
            return float(max(0, min(100, result)))
        except:
            return 50
    
    def calculate_macd(self, prices):
        try:
            if len(prices) < 26:
                return 0, 0, 0
            
            exp1 = prices.ewm(span=12, adjust=False).mean()
            exp2 = prices.ewm(span=26, adjust=False).mean()
            macd = exp1 - exp2
            signal = macd.ewm(span=9, adjust=False).mean()
            histogram = macd - signal
            
            m = macd.iloc[-1]
            s = signal.iloc[-1]
            h = histogram.iloc[-1]
            
            if pd.isna(m) or pd.isna(s) or pd.isna(h):
                return 0, 0, 0
            
            return float(m), float(s), float(h)
        except:
            return 0, 0, 0
    
    def calculate_adx(self, hist, period=14):
        try:
            if len(hist) < period * 2:
                return 25
            
            high = hist['High']
            low = hist['Low']
            close = hist['Close']
            
            plus_dm = high.diff()
            minus_dm = -low.diff()
            plus_dm[plus_dm < 0] = 0
            minus_dm[minus_dm < 0] = 0
            
            tr1 = high - low
            tr2 = abs(high - close.shift())
            tr3 = abs(low - close.shift())
            tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
            
            atr = tr.rolling(window=period).mean()
            
            plus_di = 100 * (plus_dm.rolling(window=period).mean() / atr)
            minus_di = 100 * (minus_dm.rolling(window=period).mean() / atr)
            
            dx = 100 * abs(plus_di - minus_di) / (plus_di + minus_di + 0.0001)
            adx = dx.rolling(window=period).mean()
            
            result = adx.iloc[-1]
            if pd.isna(result) or np.isinf(result):
                return 25
            
            return float(max(0, min(100, result)))
        except:
            return 25
    
    def predict_entry_exit_dates(self, hist, current_price, signals):
        try:
            close = hist['Close']
            avg_daily_move = abs(close.pct_change()).mean()
            
            if pd.isna(avg_daily_move) or avg_daily_move <= 0:
                avg_daily_move = 0.01
            
            entry_date = self.today
            if signals['investment_timing'] == 'BUY NOW':
                entry_date = self.today + timedelta(days=1)
            elif signals['investment_timing'] == 'BUY ON DIP':
                days_diff = abs(current_price - signals['entry_point'])
                daily_move_amount = current_price * avg_daily_move
                days_to_wait = int(days_diff / daily_move_amount) if daily_move_amount > 0 else 5
                entry_date = self.today + timedelta(days=min(max(days_to_wait, 2), 7))
            elif signals['investment_timing'] == 'ACCUMULATE':
                entry_date = self.today + timedelta(days=2)
            else:
                entry_date = self.today + timedelta(days=7)
            
            price_to_target = abs(signals['target_1'] - current_price)
            daily_move = current_price * avg_daily_move
            
            if daily_move > 0:
                days_to_target = int(price_to_target / daily_move)
                days_to_target = min(max(days_to_target, 20), 90)
            else:
                days_to_target = 45
            
            exit_date = entry_date + timedelta(days=days_to_target)
            stop_loss_date = entry_date + timedelta(days=5)
            
            return {
                'entry_date': entry_date,
                'exit_date': exit_date,
                'stop_loss_check_date': stop_loss_date,
                'holding_days': days_to_target
            }
        except:
            return {
                'entry_date': self.today + timedelta(days=1),
                'exit_date': self.today + timedelta(days=45),
                'stop_loss_check_date': self.today + timedelta(days=5),
                'holding_days': 45
            }
    
    def generate_investment_signals(self, hist, current_price):
        try:
            close_prices = hist['Close']
            
            if len(close_prices) < 30:
                return None
            
            sma_20 = close_prices.rolling(window=20).mean().iloc[-1] if len(close_prices) >= 20 else current_price
            sma_50 = close_prices.rolling(window=50).mean().iloc[-1] if len(close_prices) >= 50 else current_price
            sma_200 = close_prices.rolling(window=200).mean().iloc[-1] if len(close_prices) >= 200 else current_price
            
            high_52w = hist['High'].max()
            low_52w = hist['Low'].min()
            
            support = hist['Low'].iloc[-30:].min()
            resistance = hist['High'].iloc[-30:].max()
            
            if pd.isna(support) or pd.isna(resistance) or resistance <= support:
                return None
            
            rsi = self.calculate_rsi(close_prices)
            macd, macd_signal, macd_hist = self.calculate_macd(close_prices)
            adx = self.calculate_adx(hist)
            
            bb_upper, bb_middle, bb_lower = self.calculate_bollinger_bands(close_prices)
            if bb_upper is None:
                bb_upper, bb_middle, bb_lower = resistance, current_price, support
            
            fib_levels = self.calculate_fibonacci_levels(hist)
            if fib_levels is None:
                return None
            
            price_range = resistance - support
            entry_point = support + (price_range * 0.12)
            profit_target_1 = fib_levels['level_61.8']
            profit_target_2 = resistance * 0.97
            stop_loss = support * 1.015
            
            if profit_target_1 <= current_price:
                profit_target_1 = current_price * 1.08
            
            investment_timing = "WAIT"
            timing_reason = ""
            risk_level = "MEDIUM"
            confidence_score = 50
            
            bullish_signals = 0
            total_signals = 0
            
            if current_price > sma_20:
                bullish_signals += 1
            total_signals += 1
            
            if current_price > sma_50:
                bullish_signals += 1
            total_signals += 1
            
            if sma_20 > sma_50:
                bullish_signals += 1
            total_signals += 1
            
            if macd > macd_signal:
                bullish_signals += 1
            total_signals += 1
            
            if macd_hist > 0:
                bullish_signals += 1
            total_signals += 1
            
            if 30 < rsi < 70:
                bullish_signals += 1
            total_signals += 1
            
            if adx > 25:
                bullish_signals += 1
            total_signals += 1
            
            if current_price > bb_lower and current_price < bb_upper:
                bullish_signals += 1
            total_signals += 1
            
            volume_increasing = False
            if len(hist) >= 20:
                vol_recent = hist['Volume'].iloc[-5:].mean()
                vol_past = hist['Volume'].iloc[-20:-5].mean()
                volume_increasing = vol_recent > vol_past if vol_past > 0 else False
            
            if volume_increasing:
                bullish_signals += 1
            total_signals += 1
            
            base_confidence = (bullish_signals / total_signals) * 100
            
            if current_price <= entry_point and rsi < 35 and macd > macd_signal and adx > 25:
                investment_timing = "BUY NOW"
                timing_reason = "Strong oversold bounce setup with bullish MACD & strong trend"
                risk_level = "LOW"
                confidence_score = min(base_confidence + 15, 95)
                
            elif current_price <= entry_point * 1.05 and rsi < 40 and current_price > sma_20 and sma_20 > sma_50:
                investment_timing = "BUY NOW"
                timing_reason = "Perfect entry - Price above SMA20>SMA50, healthy RSI, near support"
                risk_level = "LOW"
                confidence_score = min(base_confidence + 12, 92)
                
            elif current_price > sma_20 and sma_20 > sma_50 and current_price > sma_200 and rsi < 55 and adx > 25:
                investment_timing = "BUY NOW"
                timing_reason = "Confirmed uptrend - All SMAs aligned, strong momentum, healthy RSI"
                risk_level = "LOW-MEDIUM"
                confidence_score = min(base_confidence + 10, 90)
                
            elif macd > macd_signal and macd_hist > 0 and rsi < 50 and current_price > sma_20:
                investment_timing = "ACCUMULATE"
                timing_reason = "Bullish MACD crossover with uptrend - Buy in parts"
                risk_level = "MEDIUM"
                confidence_score = min(base_confidence + 8, 85)
                
            elif current_price < entry_point * 1.15 and rsi < 50 and current_price > bb_lower:
                investment_timing = "BUY ON DIP"
                timing_reason = "Near entry zone - Wait for small pullback to support"
                risk_level = "MEDIUM"
                confidence_score = min(base_confidence + 5, 80)
                
            elif rsi > 70 or current_price > bb_upper:
                investment_timing = "WAIT"
                timing_reason = "Overbought - High risk of correction"
                risk_level = "HIGH"
                confidence_score = max(base_confidence - 15, 30)
                
            elif current_price > resistance * 0.95:
                investment_timing = "WAIT"
                timing_reason = "Near resistance - Risk of rejection"
                risk_level = "HIGH"
                confidence_score = max(base_confidence - 10, 35)
                
            elif current_price < sma_20 < sma_50:
                investment_timing = "WAIT"
                timing_reason = "Downtrend - Wait for trend reversal"
                risk_level = "HIGH"
                confidence_score = max(base_confidence - 20, 25)
                
            else:
                investment_timing = "MONITOR"
                timing_reason = "Mixed signals - Track for clearer entry opportunity"
                risk_level = "MEDIUM"
                confidence_score = base_confidence
            
            potential_gain = ((profit_target_1 - current_price) / current_price) * 100
            potential_loss = ((current_price - stop_loss) / current_price) * 100
            
            return {
                'entry_point': float(entry_point),
                'current_price': float(current_price),
                'stop_loss': float(stop_loss),
                'target_1': float(profit_target_1),
                'target_2': float(profit_target_2),
                'support': float(support),
                'resistance': float(resistance),
                'rsi': float(rsi),
                'macd': float(macd),
                'macd_signal': float(macd_signal),
                'macd_histogram': float(macd_hist),
                'adx': float(adx),
                'bb_upper': float(bb_upper),
                'bb_lower': float(bb_lower),
                'sma_20': float(sma_20),
                'sma_50': float(sma_50),
                'investment_timing': investment_timing,
                'timing_reason': timing_reason,
                'risk_level': risk_level,
                'confidence_score': round(confidence_score, 1),
                'bullish_signals': f"{bullish_signals}/{total_signals}",
                'potential_gain': float(potential_gain),
                'potential_loss': float(potential_loss),
                'distance_to_52w_high': float(((high_52w - current_price) / current_price) * 100),
                'fib_levels': fib_levels
            }
        except Exception as e:
            return None
    
    def calculate_investment_allocation(self, stock, rank, total_stocks):
        try:
            signals = stock['signals']
            risk_level = signals['risk_level']
            
            risk_weights = {
                'LOW': 0.18,
                'LOW-MEDIUM': 0.15,
                'MEDIUM': 0.12,
                'MEDIUM-HIGH': 0.08,
                'HIGH': 0.05
            }
            
            base_allocation = risk_weights.get(risk_level, 0.10)
            
            confidence_boost = max((signals['confidence_score'] - 80) / 100, 0)
            base_allocation = base_allocation * (1 + confidence_boost)
            
            rank_factor = 1 - ((rank - 1) * 0.04)
            rank_factor = max(rank_factor, 0.6)
            
            final_allocation = base_allocation * rank_factor
            
            investment_amount = self.investment_capital * final_allocation
            
            current_price = stock['current_price']
            if current_price <= 0:
                return None
            
            shares_to_buy = max(int(investment_amount / current_price), 1)
            actual_investment = shares_to_buy * current_price
            
            if actual_investment <= 0:
                return None
            
            expected_return = actual_investment * (signals['potential_gain'] / 100)
            exit_value = actual_investment + expected_return
            roi_percentage = (expected_return / actual_investment) * 100
            
            return {
                'allocation_percentage': float(final_allocation * 100),
                'investment_amount': float(actual_investment),
                'shares_to_buy': int(shares_to_buy),
                'expected_return': float(expected_return),
                'exit_value': float(exit_value),
                'roi_percentage': float(roi_percentage)
            }
        except:
            return None
    
    def analyze_stocks(self):
        print(f"\nAnalyzing {len(self.stock_data)} stocks for high-confidence opportunities...")
        print(f"Minimum confidence threshold: {self.min_confidence}%")
        print("=" * 80)
        
        for symbol, data in self.stock_data.items():
            try:
                hist = data['history']
                signals = self.generate_investment_signals(hist, data['current_price'])
                
                if signals is None:
                    continue
                
                close_prices = hist['Close']
                
                price_change_1w = 0
                price_change_1m = 0
                
                if len(close_prices) >= 5:
                    price_change_1w = ((close_prices.iloc[-1] - close_prices.iloc[-5]) / close_prices.iloc[-5]) * 100
                
                if len(close_prices) >= 20:
                    price_change_1m = ((close_prices.iloc[-1] - close_prices.iloc[-20]) / close_prices.iloc[-20]) * 100
                
                momentum = self.calculate_momentum_score(hist)
                quality_score = (signals['confidence_score'] * 0.7) + (momentum * 0.3)
                
                dates = self.predict_entry_exit_dates(hist, data['current_price'], signals)
                
                self.analyzed_stocks.append({
                    'symbol': symbol,
                    'name': data['name'],
                    'current_price': data['current_price'],
                    'change_1w': float(price_change_1w),
                    'change_1m': float(price_change_1m),
                    'quality_score': float(quality_score),
                    'history': hist,
                    'signals': signals,
                    'dates': dates
                })
            except Exception as e:
                continue
        
        if not self.analyzed_stocks:
            print("\n⚠️  Failed to analyze any stocks. Please check your internet connection.")
            self.top_stocks = []
            return
        
        self.analyzed_stocks.sort(key=lambda x: x['signals']['confidence_score'], reverse=True)
        
        high_confidence_stocks = [
            s for s in self.analyzed_stocks 
            if s['signals']['confidence_score'] >= self.min_confidence
            and s['signals']['investment_timing'] in ['BUY NOW', 'BUY ON DIP', 'ACCUMULATE']
        ]
        
        print(f"\n{'='*80}")
        print(f"ANALYSIS RESULTS:")
        print(f"{'='*80}")
        print(f"Total stocks analyzed: {len(self.analyzed_stocks)}")
        print(f"Stocks with {self.min_confidence}%+ confidence: {len(high_confidence_stocks)}")
        
        if high_confidence_stocks:
            print(f"Buy NOW: {sum(1 for s in high_confidence_stocks if s['signals']['investment_timing'] == 'BUY NOW')}")
            print(f"ACCUMULATE: {sum(1 for s in high_confidence_stocks if s['signals']['investment_timing'] == 'ACCUMULATE')}")
            print(f"Buy on DIP: {sum(1 for s in high_confidence_stocks if s['signals']['investment_timing'] == 'BUY ON DIP')}")
        
        if not high_confidence_stocks:
            print(f"\n⚠️  NO STOCKS found with confidence >= {self.min_confidence}%")
            print(f"Current market conditions may not be favorable for high-confidence entries.")
            print(f"\nTop 5 stocks by confidence (below threshold):")
            for i, stock in enumerate(self.analyzed_stocks[:5], 1):
                print(f"{i}. {stock['name']}: {stock['signals']['confidence_score']}% - {stock['signals']['investment_timing']}")
            self.top_stocks = []
            return
        
        print(f"\n{'='*80}")
        print(f"HIGH CONFIDENCE INVESTMENT OPPORTUNITIES (≥{self.min_confidence}%)")
        print(f"Total Investment Capital: ₹{self.investment_capital:,.2f}")
        print(f"Analysis Date: {self.today.strftime('%d %B %Y, %I:%M %p IST')}")
        print(f"{'='*80}\n")
        
        total_invested = 0
        total_expected_return = 0
        valid_stocks = []
        
        for i, stock in enumerate(high_confidence_stocks, 1):
            allocation = self.calculate_investment_allocation(stock, i, len(high_confidence_stocks))
            
            if allocation is None or allocation['investment_amount'] <= 0:
                continue
            
            stock['allocation'] = allocation
            valid_stocks.append(stock)
            
            signals = stock['signals']
            dates = stock['dates']
            
            total_invested += allocation['investment_amount']
            total_expected_return += allocation['expected_return']
            
            print(f"\n{'='*80}")
            print(f"STOCK #{len(valid_stocks)}: {stock['name']} ({stock['symbol'].replace('.NS', '')})")
            print(f"CONFIDENCE: {signals['confidence_score']}% | QUALITY: {stock['quality_score']:.1f}/100")
            print(f"{'='*80}")
            
            print(f"\n📊 CURRENT STATUS:")
            print(f"   Price: ₹{stock['current_price']:.2f} | 1W: {stock['change_1w']:+.2f}% | 1M: {stock['change_1m']:+.2f}%")
            print(f"   RSI: {signals['rsi']:.1f} | MACD: {signals['macd']:.2f} | ADX: {signals['adx']:.1f}")
            print(f"   Bullish Signals: {signals['bullish_signals']}")
            
            print(f"\n💰 INVESTMENT RECOMMENDATION:")
            print(f"   ⭐ Action: {signals['investment_timing']} (Risk: {signals['risk_level']})")
            print(f"   Reason: {signals['timing_reason']}")
            
            print(f"\n📅 SPECIFIC DATES:")
            print(f"   ✓ BUY DATE: {dates['entry_date'].strftime('%d %B %Y (%A)')}")
            print(f"   ✓ EXIT DATE: {dates['exit_date'].strftime('%d %B %Y (%A)')}")
            print(f"   ✓ Holding Period: {dates['holding_days']} days ({dates['holding_days']//7} weeks)")
            print(f"   ✓ Stop-Loss Review: {dates['stop_loss_check_date'].strftime('%d %B %Y')}")
            
            print(f"\n💵 INVESTMENT DETAILS:")
            print(f"   Portfolio Allocation: {allocation['allocation_percentage']:.2f}%")
            print(f"   Amount to Invest: ₹{allocation['investment_amount']:,.2f}")
            print(f"   Shares to Buy: {allocation['shares_to_buy']} shares @ ₹{stock['current_price']:.2f}")
            
            print(f"\n🎯 PRICE TARGETS:")
            print(f"   Entry: ₹{signals['entry_point']:.2f}")
            print(f"   Stop Loss: ₹{signals['stop_loss']:.2f} (Risk: {signals['potential_loss']:.1f}%)")
            print(f"   Target 1: ₹{signals['target_1']:.2f} (Book 50-70% profit)")
            print(f"   Target 2: ₹{signals['target_2']:.2f} (Exit remaining)")
            print(f"   Support: ₹{signals['support']:.2f} | Resistance: ₹{signals['resistance']:.2f}")
            
            print(f"\n📈 EXPECTED RETURNS:")
            print(f"   Expected Profit: ₹{allocation['expected_return']:,.2f}")
            print(f"   Exit Value: ₹{allocation['exit_value']:,.2f}")
            print(f"   ROI: {allocation['roi_percentage']:.2f}% | Gain: {signals['potential_gain']:.2f}%")
        
        if not valid_stocks:
            print("\n⚠️  No valid allocations could be calculated")
            self.top_stocks = []
            return
        
        print(f"\n\n{'='*80}")
        print(f"PORTFOLIO SUMMARY - {len(valid_stocks)} HIGH CONFIDENCE STOCKS")
        print(f"{'='*80}")
        print(f"Total Investment: ₹{total_invested:,.2f} ({(total_invested/self.investment_capital)*100:.1f}% of capital)")
        print(f"Expected Returns: ₹{total_expected_return:,.2f}")
        print(f"Total Exit Value: ₹{total_invested + total_expected_return:,.2f}")
        
        if total_invested > 0:
            print(f"Portfolio ROI: {(total_expected_return/total_invested)*100:.2f}%")
        
        print(f"Average Holding: {sum(s['dates']['holding_days'] for s in valid_stocks)/len(valid_stocks):.0f} days")
        print(f"Average Confidence: {sum(s['signals']['confidence_score'] for s in valid_stocks)/len(valid_stocks):.1f}%")
        
        remaining = self.investment_capital - total_invested
        if remaining > 1000:
            print(f"\n💡 Remaining Capital: ₹{remaining:,.2f} ({(remaining/self.investment_capital)*100:.1f}%)")
            print(f"   Keep as emergency fund or deploy when new opportunities arise")
        
        self.top_stocks = valid_stocks
    
    def plot_investment_dashboard(self):
        if not hasattr(self, 'top_stocks') or not self.top_stocks:
            print("\n⚠️  No high-confidence stocks to visualize")
            return
        
        try:
            num_stocks = min(len(self.top_stocks), 10)
            rows = (num_stocks + 2) // 3
            
            fig = plt.figure(figsize=(20, 5*rows))
            title = f'High Confidence Investment Opportunities (≥{self.min_confidence}%) - {num_stocks} Stocks\n'
            title += f'Generated: {self.today.strftime("%d %B %Y, %I:%M %p IST")}'
            fig.suptitle(title, fontsize=16, fontweight='bold', y=0.998)
            
            for idx, stock in enumerate(self.top_stocks[:num_stocks], 1):
                ax = plt.subplot(rows, 3, idx)
                hist = stock['history']
                signals = stock['signals']
                allocation = stock['allocation']
                dates = stock['dates']
                
                ax.plot(hist.index, hist['Close'], color='#00A3E0', linewidth=2.5, label='Price', zorder=5)
                
                sma_20 = hist['Close'].rolling(window=20).mean()
                if len(hist) >= 50:
                    sma_50 = hist['Close'].rolling(window=50).mean()
                    ax.plot(hist.index, sma_50, color='#FF9800', linewidth=1.5, 
                           linestyle='--', label='SMA 50', alpha=0.7)
                
                ax.plot(hist.index, sma_20, color='#86BC25', linewidth=1.5, 
                       linestyle='--', label='SMA 20', alpha=0.7)
                
                ax.axhline(y=signals['entry_point'], color='#00CC88', linestyle='-.', 
                          linewidth=2, label='Entry', alpha=0.8, zorder=3)
                ax.axhline(y=signals['target_1'], color='#4CAF50', linestyle=':', 
                          linewidth=2, label='Target', alpha=0.8, zorder=3)
                ax.axhline(y=signals['stop_loss'], color='#FF4444', linestyle=':', 
                          linewidth=2, label='Stop Loss', alpha=0.8, zorder=3)
                
                ax.fill_between(hist.index, hist['Close'], alpha=0.08, color='#00A3E0')
                
                timing_colors = {
                    'BUY NOW': '#00CC88',
                    'BUY ON DIP': '#FFA500',
                    'ACCUMULATE': '#4169E1'
                }
                title_color = timing_colors.get(signals['investment_timing'], '#000000')
                
                title_text = f"#{idx}. {stock['name']}\n"
                title_text += f"Confidence: {signals['confidence_score']}% | {signals['investment_timing']}\n"
                title_text += f"Invest ₹{allocation['investment_amount']:,.0f} on {dates['entry_date'].strftime('%d-%b')}\n"
                title_text += f"Exit: {dates['exit_date'].strftime('%d-%b')} | Expected: +₹{allocation['expected_return']:,.0f} ({allocation['roi_percentage']:.1f}%)"
                
                ax.set_title(title_text, fontsize=7.5, fontweight='bold', pad=8, color=title_color)
                
                ax.set_xlabel('Date', fontsize=7)
                ax.set_ylabel('Price (₹)', fontsize=7)
                ax.legend(loc='upper left', fontsize=6, framealpha=0.9, ncol=2)
                ax.grid(True, alpha=0.2, linestyle=':')
                ax.tick_params(labelsize=6)
            
            plt.tight_layout()
            plt.subplots_adjust(top=0.97, hspace=0.4, wspace=0.25)
            
            filename = f'high_confidence_stocks_{self.today.strftime("%Y%m%d_%H%M")}.png'
            plt.savefig(filename, dpi=150, bbox_inches='tight')
            print(f"\n✓ Dashboard saved as '{filename}'")
            plt.show()
        except Exception as e:
            print(f"\n✗ Error creating dashboard: {str(e)}")
    
    def save_investment_plan(self):
        if not hasattr(self, 'top_stocks') or not self.top_stocks:
            print("\n⚠️  No stocks to save")
            return
        
        try:
            filename = f'investment_plan_{self.min_confidence}pct_{self.today.strftime("%Y%m%d_%H%M")}.csv'
            
            plan_data = []
            for stock in self.top_stocks:
                signals = stock['signals']
                allocation = stock['allocation']
                dates = stock['dates']
                
                plan_data.append({
                    'Rank': self.top_stocks.index(stock) + 1,
                    'Stock': stock['name'],
                    'Symbol': stock['symbol'].replace('.NS', ''),
                    'Confidence %': signals['confidence_score'],
                    'Current Price': f"₹{stock['current_price']:.2f}",
                    'Investment Action': signals['investment_timing'],
                    'Risk Level': signals['risk_level'],
                    'Buy Date': dates['entry_date'].strftime('%d-%b-%Y'),
                    'Exit Date': dates['exit_date'].strftime('%d-%b-%Y'),
                    'Holding Days': dates['holding_days'],
                    'Invest Amount': f"₹{allocation['investment_amount']:,.2f}",
                    'Shares': allocation['shares_to_buy'],
                    'Entry Price': f"₹{signals['entry_point']:.2f}",
                    'Stop Loss': f"₹{signals['stop_loss']:.2f}",
                    'Target': f"₹{signals['target_1']:.2f}",
                    'Expected Return': f"₹{allocation['expected_return']:,.2f}",
                    'ROI %': f"{allocation['roi_percentage']:.2f}%",
                    'RSI': f"{signals['rsi']:.1f}",
                    'ADX': f"{signals['adx']:.1f}",
                    'Bullish Signals': signals['bullish_signals'],
                    'Reason': signals['timing_reason']
                })
            
            df = pd.DataFrame(plan_data)
            df.to_csv(filename, index=False)
            print(f"✓ Investment plan saved to '{filename}'")
            
            total_investment = sum(s['allocation']['investment_amount'] for s in self.top_stocks)
            total_return = sum(s['allocation']['expected_return'] for s in self.top_stocks)
            
            summary_data = {
                'Total Stocks': len(self.top_stocks),
                'Total Investment': f"₹{total_investment:,.2f}",
                'Expected Returns': f"₹{total_return:,.2f}",
                'Portfolio ROI': f"{(total_return/total_investment)*100:.2f}%" if total_investment > 0 else "0%",
                'Avg Confidence': f"{sum(s['signals']['confidence_score'] for s in self.top_stocks) / len(self.top_stocks):.1f}%",
                'Analysis Date': self.today.strftime('%d-%b-%Y %I:%M %p')
            }
            
            summary_filename = f'portfolio_summary_{self.today.strftime("%Y%m%d_%H%M")}.csv'
            pd.DataFrame([summary_data]).to_csv(summary_filename, index=False)
            print(f"✓ Portfolio summary saved to '{summary_filename}'")
        except Exception as e:
            print(f"✗ Error saving files: {str(e)}")

def main():
    print("\n" + "="*80)
    print("   🎯 HIGH CONFIDENCE INDIAN STOCK INVESTMENT ADVISOR")
    print("   Only Stocks with 80%+ Confidence & Strong Technical Setup")
    print("="*80 + "\n")
    
    try:
        capital = input("Enter investment capital (default ₹100,000): ").strip()
        if capital and capital.replace(',', '').replace('.', '').isdigit():
            capital = float(capital.replace(',', ''))
        else:
            capital = 100000
        
        min_conf = input("Enter minimum confidence % (default 80): ").strip()
        if min_conf and min_conf.isdigit():
            min_conf = int(min_conf)
        else:
            min_conf = 80
        
        print(f"\n✓ Investment Capital: ₹{capital:,.2f}")
        print(f"✓ Minimum Confidence: {min_conf}%")
        print(f"\nStarting analysis of 100+ NSE stocks...")
        
        advisor = HighConfidenceStockAdvisor(investment_capital=capital, min_confidence=min_conf)
        
        advisor.fetch_latest_stock_data()
        
        if not advisor.stock_data:
            print("\n✗ Failed to fetch stock data. Please check your internet connection.")
            return
        
        advisor.analyze_stocks()
        
        if hasattr(advisor, 'top_stocks') and advisor.top_stocks:
            print("\n\nGenerating investment dashboard...")
            advisor.plot_investment_dashboard()
            
            save_option = input("\nSave detailed plan & summary to CSV? (y/n): ").strip().lower()
            if save_option == 'y':
                advisor.save_investment_plan()
        else:
            print("\n💡 TIP: Try lowering the confidence threshold (e.g., 70%) to see more opportunities.")
        
        print("\n" + "="*80)
        print("⚠️  CRITICAL DISCLAIMER:")
        print("="*80)
        print("This is EDUCATIONAL ANALYSIS ONLY, not financial advice.")
        print("Confidence scores are based on technical indicators and historical data.")
        print("Past performance does NOT guarantee future results.")
        print("\n🚨 BEFORE INVESTING:")
        print("1. Consult a SEBI-registered financial advisor")
        print("2. Understand your risk tolerance and investment goals")
        print("3. Never invest money you cannot afford to lose")
        print("4. Diversify across asset classes, not just stocks")
        print("5. Conduct your own research (DYOR)")
        print("6. Markets are unpredictable - manage risk with stop-losses")
        print("="*80 + "\n")
    
    except KeyboardInterrupt:
        print("\n\n⚠️  Analysis interrupted by user")
    except Exception as e:
        print(f"\n✗ An error occurred: {str(e)}")
        print("Please try again or check your internet connection.")

if __name__ == '__main__':
    main()
