# filename: random_image_generator_web.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from PIL import Image, ImageDraw
import random
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import requests
from io import BytesIO
import time

def random_color():
    return (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))

def fetch_random_image_unsplash(width=800, height=600):
    try:
        url = f'https://source.unsplash.com/random/{width}x{height}'
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            image = Image.open(BytesIO(response.content))
            return image, 'Unsplash Random'
        return None, None
    except Exception as e:
        print(f"Error fetching from Unsplash: {e}")
        return None, None

def fetch_random_image_picsum(width=800, height=600):
    try:
        image_id = random.randint(1, 1000)
        url = f'https://picsum.photos/id/{image_id}/{width}/{height}'
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            image = Image.open(BytesIO(response.content))
            return image, 'Picsum Photos'
        return None, None
    except Exception as e:
        print(f"Error fetching from Picsum: {e}")
        return None, None

def fetch_random_image_loremflickr(width=800, height=600):
    try:
        topics = ['nature', 'city', 'technology', 'food', 'animals', 'abstract', 'architecture', 'art']
        topic = random.choice(topics)
        url = f'https://loremflickr.com/{width}/{height}/{topic}'
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            image = Image.open(BytesIO(response.content))
            return image, f'LoremFlickr - {topic.title()}'
        return None, None
    except Exception as e:
        print(f"Error fetching from LoremFlickr: {e}")
        return None, None

def fetch_random_image_placeholder(width=800, height=600):
    try:
        colors = ['FF6B6B', '4ECDC4', '45B7D1', 'FFA07A', '98D8C8', 'F7DC6F', 'BB8FCE']
        color = random.choice(colors)
        url = f'https://via.placeholder.com/{width}x{height}/{color}/FFFFFF?text=Random+Image'
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            image = Image.open(BytesIO(response.content))
            return image, 'Placeholder'
        return None, None
    except Exception as e:
        print(f"Error fetching placeholder: {e}")
        return None, None

def fetch_random_dog_image():
    try:
        url = 'https://dog.ceo/api/breeds/image/random'
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            data = response.json()
            img_url = data['message']
            img_response = requests.get(img_url, timeout=10)
            image = Image.open(BytesIO(img_response.content))
            return image, 'Random Dog'
        return None, None
    except Exception as e:
        print(f"Error fetching dog image: {e}")
        return None, None

def fetch_random_cat_image():
    try:
        url = 'https://api.thecatapi.com/v1/images/search'
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            data = response.json()
            img_url = data[0]['url']
            img_response = requests.get(img_url, timeout=10)
            image = Image.open(BytesIO(img_response.content))
            return image, 'Random Cat'
        return None, None
    except Exception as e:
        print(f"Error fetching cat image: {e}")
        return None, None

def draw_random_circles(width=800, height=600, num_shapes=50):
    image = Image.new('RGB', (width, height), color=random_color())
    draw = ImageDraw.Draw(image)
    
    for _ in range(num_shapes):
        x1 = random.randint(0, width)
        y1 = random.randint(0, height)
        radius = random.randint(20, 150)
        x2 = x1 + radius
        y2 = y1 + radius
        
        color = random_color()
        draw.ellipse([x1, y1, x2, y2], fill=color, outline=random_color(), width=random.randint(1, 5))
    
    return image

def draw_random_rectangles(width=800, height=600, num_shapes=40):
    image = Image.new('RGB', (width, height), color=random_color())
    draw = ImageDraw.Draw(image)
    
    for _ in range(num_shapes):
        x1 = random.randint(0, width)
        y1 = random.randint(0, height)
        x2 = random.randint(x1, width)
        y2 = random.randint(y1, height)
        
        color = random_color()
        draw.rectangle([x1, y1, x2, y2], fill=color, outline=random_color(), width=random.randint(1, 3))
    
    return image

def draw_random_lines(width=800, height=600, num_lines=100):
    image = Image.new('RGB', (width, height), color=(0, 0, 0))
    draw = ImageDraw.Draw(image)
    
    for _ in range(num_lines):
        x1 = random.randint(0, width)
        y1 = random.randint(0, height)
        x2 = random.randint(0, width)
        y2 = random.randint(0, height)
        
        color = random_color()
        draw.line([x1, y1, x2, y2], fill=color, width=random.randint(1, 5))
    
    return image

def draw_random_polygons(width=800, height=600, num_shapes=30):
    image = Image.new('RGB', (width, height), color=random_color())
    draw = ImageDraw.Draw(image)
    
    for _ in range(num_shapes):
        num_points = random.randint(3, 8)
        points = [(random.randint(0, width), random.randint(0, height)) for _ in range(num_points)]
        
        color = random_color()
        draw.polygon(points, fill=color, outline=random_color())
    
    return image

def draw_gradient_noise(width=800, height=600):
    image = Image.new('RGB', (width, height))
    pixels = image.load()
    
    for x in range(width):
        for y in range(height):
            r = int((x / width) * 255)
            g = int((y / height) * 255)
            b = random.randint(0, 255)
            pixels[x, y] = (r, g, b)
    
    return image

def draw_pixel_art(width=800, height=600, pixel_size=20):
    image = Image.new('RGB', (width, height))
    draw = ImageDraw.Draw(image)
    
    for x in range(0, width, pixel_size):
        for y in range(0, height, pixel_size):
            color = random_color()
            draw.rectangle([x, y, x + pixel_size, y + pixel_size], fill=color)
    
    return image

def generate_random_image():
    generated_styles = [
        ('Circles', draw_random_circles),
        ('Rectangles', draw_random_rectangles),
        ('Lines', draw_random_lines),
        ('Polygons', draw_random_polygons),
        ('Gradient Noise', draw_gradient_noise),
        ('Pixel Art', draw_pixel_art)
    ]
    
    web_sources = [
        ('Web Image', fetch_random_image_unsplash),
        ('Web Image', fetch_random_image_picsum),
        ('Web Image', fetch_random_image_loremflickr),
        ('Web Image', fetch_random_dog_image),
        ('Web Image', fetch_random_cat_image),
        ('Web Image', fetch_random_image_placeholder)
    ]
    
    all_sources = generated_styles + web_sources
    
    max_attempts = 3
    for attempt in range(max_attempts):
        style_name, style_func = random.choice(all_sources)
        
        if style_func in [f for _, f in generated_styles]:
            print(f"Generating: {style_name}")
            return style_func(), style_name
        else:
            print(f"Fetching from internet: {style_name} (attempt {attempt + 1})")
            image, source_name = style_func()
            if image is not None:
                return image, source_name
            time.sleep(0.5)
    
    print("Fallback to generated image")
    style_name, style_func = random.choice(generated_styles)
    return style_func(), style_name

def display_images(num_images=6):
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    fig.suptitle('Random Generated & Web Images', fontsize=16, fontweight='bold')
    
    for ax in axes.flat:
        image, style_name = generate_random_image()
        ax.imshow(image)
        ax.set_title(style_name, fontsize=12, fontweight='bold')
        ax.axis('off')
    
    plt.tight_layout()
    plt.show()

def continuous_generation():
    fig, ax = plt.subplots(figsize=(10, 8))
    ax.axis('off')
    
    def update(frame):
        ax.clear()
        ax.axis('off')
        image, style_name = generate_random_image()
        ax.imshow(image)
        ax.set_title(f'{style_name} - Frame {frame}', fontsize=14, fontweight='bold')
        return ax,
    
    ani = FuncAnimation(fig, update, frames=range(100), interval=2000, blit=False)
    plt.show()

def save_random_images(num_images=5, output_dir='random_images'):
    import os
    os.makedirs(output_dir, exist_ok=True)
    
    for i in range(num_images):
        image, style_name = generate_random_image()
        filename = f'{output_dir}/random_image_{i+1}_{style_name.replace(" ", "_")}.png'
        image.save(filename)
        print(f'Saved: {filename}')

def display_web_only_images(num_images=6):
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    fig.suptitle('Random Web Images Only', fontsize=16, fontweight='bold')
    
    web_sources = [
        fetch_random_image_unsplash,
        fetch_random_image_picsum,
        fetch_random_image_loremflickr,
        fetch_random_dog_image,
        fetch_random_cat_image
    ]
    
    for ax in axes.flat:
        source = random.choice(web_sources)
        image, style_name = source()
        
        if image is None:
            image = draw_random_circles()
            style_name = 'Fallback Generated'
        
        ax.imshow(image)
        ax.set_title(style_name, fontsize=12, fontweight='bold')
        ax.axis('off')
    
    plt.tight_layout()
    plt.show()

if __name__ == '__main__':
    print("Random Image Generator (with Web Images)")
    print("=" * 50)
    print("\nChoose an option:")
    print("1. Display 6 random images (generated + web)")
    print("2. Continuously generate images (1 every 2 seconds)")
    print("3. Save 5 random images to disk")
    print("4. Generate single random image")
    print("5. Display 6 web images only")
    
    choice = input("\nEnter choice (1-5): ").strip()
    
    if choice == '1':
        display_images(6)
    elif choice == '2':
        print("Press Ctrl+C to stop...")
        continuous_generation()
    elif choice == '3':
        save_random_images(5)
        print("\nImages saved successfully!")
    elif choice == '4':
        image, style_name = generate_random_image()
        plt.figure(figsize=(10, 8))
        plt.imshow(image)
        plt.title(style_name, fontsize=14, fontweight='bold')
        plt.axis('off')
        plt.show()
    elif choice == '5':
        display_web_only_images(6)
    else:
        print("Invalid choice. Displaying single image...")
        image, style_name = generate_random_image()
        plt.figure(figsize=(10, 8))
        plt.imshow(image)
        plt.title(style_name, fontsize=14, fontweight='bold')
        plt.axis('off')
        plt.show()
