# filename: nifty50_investment_analyzer_final.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, numbers
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.utils import get_column_letter
import time

warnings.filterwarnings('ignore')

STARTING_BUDGET = 1000000
RISK_FREE_RATE = 6.0
YEARS_LOOKBACK = 5
STOP_LOSS_PERCENT = 15
TAKE_PROFIT_PERCENT = 30
TOP_N_STOCKS = 10
ALLOCATION_METHOD = 'equal_weight'

NIFTY_50_TICKERS = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
    'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
    'LT.NS', 'AXISBANK.NS', 'BAJFINANCE.NS', 'ASIANPAINT.NS', 'MARUTI.NS',
    'TITAN.NS', 'SUNPHARMA.NS', 'ULTRACEMCO.NS', 'NESTLEIND.NS', 'WIPRO.NS',
    'NTPC.NS', 'HCLTECH.NS', 'M&M.NS', 'TATAMOTORS.NS', 'TECHM.NS',
    'POWERGRID.NS', 'BAJAJFINSV.NS', 'ONGC.NS', 'TATASTEEL.NS', 'ADANIENT.NS',
    'COALINDIA.NS', 'INDUSINDBK.NS', 'DIVISLAB.NS', 'GRASIM.NS', 'JSWSTEEL.NS',
    'HINDALCO.NS', 'APOLLOHOSP.NS', 'ADANIPORTS.NS', 'CIPLA.NS', 'DRREDDY.NS',
    'EICHERMOT.NS', 'BAJAJ-AUTO.NS', 'BRITANNIA.NS', 'BPCL.NS', 'HEROMOTOCO.NS',
    'TATACONSUM.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'LTIM.NS', 'SHRIRAMFIN.NS'
]


def is_valid_number(value):
    """Check if a value is a valid number (not NaN, not inf)"""
    if value is None:
        return False
    if isinstance(value, (int, float)):
        return not (np.isnan(value) or np.isinf(value))
    return False


def get_robust_current_price(stock, hist):
    """Get current price with multiple fallback methods"""
    current_price = None
    
    try:
        if not hist.empty and len(hist) > 0:
            last_close = hist['Close'].iloc[-1]
            if is_valid_number(last_close) and last_close > 0:
                return float(last_close)
    except:
        pass
    
    try:
        info = stock.info
        if 'currentPrice' in info and info['currentPrice'] is not None:
            price = info['currentPrice']
            if is_valid_number(price) and price > 0:
                return float(price)
    except:
        pass
    
    try:
        info = stock.info
        if 'regularMarketPrice' in info and info['regularMarketPrice'] is not None:
            price = info['regularMarketPrice']
            if is_valid_number(price) and price > 0:
                return float(price)
    except:
        pass
    
    try:
        if hasattr(stock, 'fast_info') and hasattr(stock.fast_info, 'last_price'):
            price = stock.fast_info.last_price
            if is_valid_number(price) and price > 0:
                return float(price)
    except:
        pass
    
    try:
        today_data = stock.history(period='1d')
        if not today_data.empty and len(today_data) > 0:
            price = today_data['Close'].iloc[-1]
            if is_valid_number(price) and price > 0:
                return float(price)
    except:
        pass
    
    try:
        recent_data = stock.history(period='5d')
        if not recent_data.empty and len(recent_data) > 0:
            close_prices = recent_data['Close'].dropna()
            if len(close_prices) > 0:
                price = close_prices.iloc[-1]
                if is_valid_number(price) and price > 0:
                    return float(price)
    except:
        pass
    
    return None


def fetch_stock_data(ticker, start_date, end_date, max_retries=3):
    """Fetch historical stock data with retry mechanism and robust validation"""
    for attempt in range(max_retries):
        try:
            stock = yf.Ticker(ticker)
            hist = stock.history(start=start_date, end=end_date)
            
            if hist.empty or len(hist) < 252:
                return None
            
            current_price = get_robust_current_price(stock, hist)
            
            if current_price is None or current_price <= 0:
                return None
            
            try:
                info = stock.info
                company_name = info.get('longName', info.get('shortName', ticker.replace('.NS', '')))
            except:
                company_name = ticker.replace('.NS', '')
            
            return {
                'ticker': ticker,
                'name': company_name,
                'history': hist,
                'current_price': float(current_price)
            }
            
        except Exception as e:
            if attempt < max_retries - 1:
                time.sleep(1)
                continue
            else:
                return None
    
    return None


def calculate_cagr(start_price, end_price, years):
    """Calculate Compound Annual Growth Rate with validation"""
    try:
        if not is_valid_number(start_price) or not is_valid_number(end_price) or not is_valid_number(years):
            return 0
        if start_price <= 0 or end_price <= 0 or years <= 0:
            return 0
        cagr = (((end_price / start_price) ** (1 / years)) - 1) * 100
        return cagr if is_valid_number(cagr) else 0
    except:
        return 0


def calculate_sharpe_ratio(returns, risk_free_rate):
    """Calculate Sharpe Ratio with validation"""
    try:
        if len(returns) == 0:
            return 0
        
        returns_clean = returns.dropna()
        if len(returns_clean) == 0:
            return 0
        
        std_dev = returns_clean.std()
        if not is_valid_number(std_dev) or std_dev == 0:
            return 0
        
        excess_returns = returns_clean.mean() * 252 - (risk_free_rate / 100)
        volatility = std_dev * np.sqrt(252)
        
        if not is_valid_number(volatility) or volatility == 0:
            return 0
        
        sharpe = excess_returns / volatility
        return sharpe if is_valid_number(sharpe) else 0
    except:
        return 0


def calculate_max_drawdown(price_series):
    """Calculate Maximum Drawdown with validation"""
    try:
        if len(price_series) == 0:
            return -10
        
        price_clean = price_series.dropna()
        if len(price_clean) == 0 or price_clean.iloc[0] <= 0:
            return -10
        
        cumulative = price_clean / price_clean.iloc[0]
        running_max = cumulative.expanding().max()
        drawdown = (cumulative - running_max) / running_max
        max_dd = drawdown.min() * 100
        
        return max_dd if is_valid_number(max_dd) else -10
    except:
        return -10


def calculate_volatility(returns):
    """Calculate annualized volatility with validation"""
    try:
        if len(returns) == 0:
            return 20
        
        returns_clean = returns.dropna()
        if len(returns_clean) == 0:
            return 20
        
        std_dev = returns_clean.std()
        if not is_valid_number(std_dev):
            return 20
        
        vol = std_dev * np.sqrt(252) * 100
        return vol if is_valid_number(vol) else 20
    except:
        return 20


def analyze_stock(stock_data):
    """Perform comprehensive analysis on stock data with robust error handling"""
    try:
        hist = stock_data['history']
        close_prices = hist['Close'].dropna()
        
        if len(close_prices) < 100:
            return None
        
        daily_returns = close_prices.pct_change().dropna()
        years = len(close_prices) / 252
        
        start_price = close_prices.iloc[0]
        end_price = close_prices.iloc[-1]
        
        if not is_valid_number(start_price) or not is_valid_number(end_price):
            return None
        
        if start_price <= 0 or end_price <= 0:
            return None
        
        cagr = calculate_cagr(start_price, end_price, years)
        sharpe = calculate_sharpe_ratio(daily_returns, RISK_FREE_RATE)
        max_dd = calculate_max_drawdown(close_prices)
        volatility = calculate_volatility(daily_returns)
        
        cumulative_return = ((end_price - start_price) / start_price) * 100
        
        ema_200_series = close_prices.ewm(span=200, adjust=False).mean()
        ema_200 = ema_200_series.iloc[-1] if len(ema_200_series) > 0 else close_prices.iloc[-1]
        
        if not is_valid_number(stock_data['current_price']):
            return None
        
        result = {
            'ticker': stock_data['ticker'],
            'name': stock_data['name'],
            'current_price': float(stock_data['current_price']),
            'cagr': float(cagr) if is_valid_number(cagr) else 0.0,
            'sharpe_ratio': float(sharpe) if is_valid_number(sharpe) else 0.0,
            'max_drawdown': float(max_dd) if is_valid_number(max_dd) else -10.0,
            'volatility': float(volatility) if is_valid_number(volatility) else 20.0,
            'cumulative_return': float(cumulative_return) if is_valid_number(cumulative_return) else 0.0,
            'ema_200': float(ema_200) if is_valid_number(ema_200) else float(stock_data['current_price']),
            'data_points': len(close_prices)
        }
        
        for key, value in result.items():
            if key not in ['ticker', 'name', 'data_points']:
                if not is_valid_number(value):
                    return None
        
        return result
    except Exception as e:
        return None


def calculate_composite_score(metrics_df):
    """Calculate composite score for ranking stocks with validation"""
    df = metrics_df.copy()
    
    df = df.dropna(subset=['cagr', 'sharpe_ratio', 'max_drawdown'])
    
    if len(df) == 0:
        return df
    
    cagr_range = df['cagr'].max() - df['cagr'].min()
    if cagr_range > 0:
        df['cagr_score'] = (df['cagr'] - df['cagr'].min()) / cagr_range * 100
    else:
        df['cagr_score'] = 50.0
    
    sharpe_range = df['sharpe_ratio'].max() - df['sharpe_ratio'].min()
    if sharpe_range > 0:
        df['sharpe_score'] = (df['sharpe_ratio'] - df['sharpe_ratio'].min()) / sharpe_range * 100
    else:
        df['sharpe_score'] = 50.0
    
    drawdown_range = df['max_drawdown'].max() - df['max_drawdown'].min()
    if drawdown_range > 0:
        df['drawdown_score'] = (df['max_drawdown'] - df['max_drawdown'].min()) / drawdown_range * 100
    else:
        df['drawdown_score'] = 50.0
    
    df['composite_score'] = (
        df['cagr_score'] * 0.40 +
        df['sharpe_score'] * 0.35 +
        df['drawdown_score'] * 0.25
    )
    
    df = df.dropna(subset=['composite_score'])
    
    return df


def allocate_capital_equal_weight(top_stocks, budget):
    """Allocate capital equally among selected stocks with validation"""
    top_stocks_clean = top_stocks[top_stocks['current_price'].notna() & (top_stocks['current_price'] > 0)].copy()
    
    if len(top_stocks_clean) == 0:
        return [], 0
    
    allocation_per_stock = budget / len(top_stocks_clean)
    
    allocations = []
    total_allocated = 0
    
    for _, stock in top_stocks_clean.iterrows():
        current_price = float(stock['current_price'])
        
        if not is_valid_number(current_price) or current_price <= 0:
            continue
        
        shares = max(1, int(allocation_per_stock / current_price))
        actual_allocation = shares * current_price
        
        allocations.append({
            'ticker': stock['ticker'],
            'allocation': float(actual_allocation),
            'shares': int(shares)
        })
        total_allocated += actual_allocation
    
    return allocations, total_allocated


def allocate_capital_risk_parity(top_stocks, budget):
    """Allocate capital inversely proportional to volatility with validation"""
    top_stocks_clean = top_stocks[
        (top_stocks['current_price'].notna()) & 
        (top_stocks['current_price'] > 0) &
        (top_stocks['volatility'].notna()) &
        (top_stocks['volatility'] > 0)
    ].copy()
    
    if len(top_stocks_clean) == 0:
        return allocate_capital_equal_weight(top_stocks, budget)
    
    top_stocks_clean['inv_volatility'] = 1 / (top_stocks_clean['volatility'] + 0.0001)
    total_inv_vol = top_stocks_clean['inv_volatility'].sum()
    
    if not is_valid_number(total_inv_vol) or total_inv_vol <= 0:
        return allocate_capital_equal_weight(top_stocks, budget)
    
    top_stocks_clean['weight'] = top_stocks_clean['inv_volatility'] / total_inv_vol
    
    allocations = []
    total_allocated = 0
    
    for _, stock in top_stocks_clean.iterrows():
        current_price = float(stock['current_price'])
        weight = float(stock['weight'])
        
        if not is_valid_number(current_price) or current_price <= 0:
            continue
        
        if not is_valid_number(weight) or weight <= 0:
            continue
        
        target_allocation = budget * weight
        shares = max(1, int(target_allocation / current_price))
        actual_allocation = shares * current_price
        
        allocations.append({
            'ticker': stock['ticker'],
            'allocation': float(actual_allocation),
            'shares': int(shares)
        })
        total_allocated += actual_allocation
    
    return allocations, total_allocated


def calculate_exit_signals(stock_data, allocation_data):
    """Calculate stop-loss, take-profit, and trailing stop signals with validation"""
    current_price = float(stock_data['current_price'])
    ema_200 = float(stock_data['ema_200'])
    shares = int(allocation_data['shares'])
    
    if not is_valid_number(current_price) or current_price <= 0:
        current_price = 100
    
    if not is_valid_number(ema_200) or ema_200 <= 0:
        ema_200 = current_price
    
    stop_loss = current_price * (1 - STOP_LOSS_PERCENT / 100)
    take_profit = current_price * (1 + TAKE_PROFIT_PERCENT / 100)
    
    trailing_stop_signal = "HOLD" if current_price > ema_200 else "EXIT"
    
    potential_profit = (take_profit - current_price) * shares
    potential_loss = (current_price - stop_loss) * shares
    
    risk_reward = potential_profit / potential_loss if potential_loss > 0 else 1.0
    
    return {
        'stop_loss_price': float(stop_loss),
        'take_profit_price': float(take_profit),
        'ema_200': float(ema_200),
        'trailing_stop_signal': trailing_stop_signal,
        'potential_profit': float(potential_profit),
        'potential_loss': float(potential_loss),
        'risk_reward_ratio': float(risk_reward)
    }


def create_excel_report(portfolio_df, all_stocks_df, filename='nifty50_investment_plan.xlsx'):
    """Create formatted Excel report with portfolio and market data"""
    wb = Workbook()
    
    ws_portfolio = wb.active
    ws_portfolio.title = "Top_Stocks_Portfolio"
    
    ws_portfolio['A1'] = "NIFTY 50 INVESTMENT PORTFOLIO"
    ws_portfolio['A1'].font = Font(size=16, bold=True, color='FFFFFF')
    ws_portfolio['A1'].fill = PatternFill(start_color='0066CC', end_color='0066CC', fill_type='solid')
    ws_portfolio['A1'].alignment = Alignment(horizontal='center', vertical='center')
    ws_portfolio.merge_cells('A1:M1')
    ws_portfolio.row_dimensions[1].height = 25
    
    ws_portfolio['A2'] = f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    ws_portfolio['A3'] = f"Total Budget: ₹{STARTING_BUDGET:,.2f}"
    ws_portfolio['A4'] = f"Allocation Method: {ALLOCATION_METHOD.replace('_', ' ').title()}"
    ws_portfolio.merge_cells('A2:D2')
    ws_portfolio.merge_cells('A3:D3')
    ws_portfolio.merge_cells('A4:D4')
    
    headers = [
        'Rank', 'Ticker', 'Company Name', 'Current Price', 'Shares to Buy', 
        'Investment Amount', 'Allocation %', 'Stop-Loss Price', 'Take-Profit Price',
        'Potential Profit', 'Potential Loss', 'Risk/Reward', 'Exit Signal (EMA200)'
    ]
    
    for col, header in enumerate(headers, start=1):
        cell = ws_portfolio.cell(row=6, column=col, value=header)
        cell.font = Font(bold=True, color='FFFFFF', size=11)
        cell.fill = PatternFill(start_color='004080', end_color='004080', fill_type='solid')
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    
    for idx, row in enumerate(dataframe_to_rows(portfolio_df, index=False, header=False), start=7):
        for col, value in enumerate(row, start=1):
            cell = ws_portfolio.cell(row=idx, column=col, value=value)
            cell.alignment = Alignment(horizontal='center', vertical='center')
            
            if col in [4, 6, 8, 9, 10, 11]:
                cell.number_format = '₹#,##0.00'
            elif col == 7:
                cell.number_format = '0.00"%"'
            elif col == 12:
                cell.number_format = '0.00'
            
            if idx % 2 == 0:
                cell.fill = PatternFill(start_color='E6F2FF', end_color='E6F2FF', fill_type='solid')
    
    total_row = len(portfolio_df) + 7
    ws_portfolio[f'A{total_row}'] = "TOTAL"
    ws_portfolio[f'A{total_row}'].font = Font(bold=True)
    ws_portfolio[f'F{total_row}'] = portfolio_df['Investment Amount'].sum()
    ws_portfolio[f'F{total_row}'].font = Font(bold=True)
    ws_portfolio[f'F{total_row}'].number_format = '₹#,##0.00'
    ws_portfolio[f'J{total_row}'] = portfolio_df['Potential Profit'].sum()
    ws_portfolio[f'J{total_row}'].font = Font(bold=True)
    ws_portfolio[f'J{total_row}'].number_format = '₹#,##0.00'
    ws_portfolio[f'K{total_row}'] = portfolio_df['Potential Loss'].sum()
    ws_portfolio[f'K{total_row}'].font = Font(bold=True)
    ws_portfolio[f'K{total_row}'].number_format = '₹#,##0.00'
    
    column_widths = [8, 15, 25, 15, 12, 18, 12, 15, 15, 15, 15, 12, 20]
    for idx, width in enumerate(column_widths, start=1):
        column_letter = get_column_letter(idx)
        ws_portfolio.column_dimensions[column_letter].width = width
    
    ws_all = wb.create_sheet(title="All_Market_Data")
    
    ws_all['A1'] = "NIFTY 50 - COMPLETE MARKET ANALYSIS (5 YEARS)"
    ws_all['A1'].font = Font(size=14, bold=True, color='FFFFFF')
    ws_all['A1'].fill = PatternFill(start_color='008000', end_color='008000', fill_type='solid')
    ws_all['A1'].alignment = Alignment(horizontal='center', vertical='center')
    ws_all.merge_cells('A1:J1')
    ws_all.row_dimensions[1].height = 25
    
    all_headers = [
        'Rank', 'Ticker', 'Company Name', 'Current Price', 'CAGR (%)', 
        'Sharpe Ratio', 'Max Drawdown (%)', 'Volatility (%)', 
        'Cumulative Return (%)', 'Composite Score'
    ]
    
    for col, header in enumerate(all_headers, start=1):
        cell = ws_all.cell(row=3, column=col, value=header)
        cell.font = Font(bold=True, color='FFFFFF', size=11)
        cell.fill = PatternFill(start_color='006600', end_color='006600', fill_type='solid')
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
    
    for idx, row in enumerate(dataframe_to_rows(all_stocks_df, index=False, header=False), start=4):
        for col, value in enumerate(row, start=1):
            cell = ws_all.cell(row=idx, column=col, value=value)
            cell.alignment = Alignment(horizontal='center', vertical='center')
            
            if col == 4:
                cell.number_format = '₹#,##0.00'
            elif col in [5, 7, 8, 9, 10]:
                cell.number_format = '0.00'
            elif col == 6:
                cell.number_format = '0.00'
            
            if idx <= 13:
                cell.fill = PatternFill(start_color='D4EDDA', end_color='D4EDDA', fill_type='solid')
            elif idx % 2 == 0:
                cell.fill = PatternFill(start_color='F0F0F0', end_color='F0F0F0', fill_type='solid')
    
    all_column_widths = [8, 15, 25, 15, 12, 12, 15, 12, 18, 15]
    for idx, width in enumerate(all_column_widths, start=1):
        column_letter = get_column_letter(idx)
        ws_all.column_dimensions[column_letter].width = width
    
    wb.save(filename)
    print(f"\n✅ Excel report saved: {filename}")


def main():
    """Main execution function"""
    print("=" * 80)
    print("NIFTY 50 INVESTMENT ANALYZER - 5 YEAR HISTORICAL ANALYSIS (FINAL)")
    print("=" * 80)
    print(f"\n📊 Configuration:")
    print(f"   Budget: ₹{STARTING_BUDGET:,.2f}")
    print(f"   Lookback Period: {YEARS_LOOKBACK} years")
    print(f"   Stocks to Select: Top {TOP_N_STOCKS}")
    print(f"   Allocation Method: {ALLOCATION_METHOD.replace('_', ' ').title()}")
    print(f"   Stop-Loss: {STOP_LOSS_PERCENT}% | Take-Profit: {TAKE_PROFIT_PERCENT}%")
    print("\n" + "=" * 80)
    
    end_date = datetime.now()
    start_date = end_date - timedelta(days=YEARS_LOOKBACK * 365 + 30)
    
    print(f"\n📅 Fetching data from {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")
    print(f"⏳ Analyzing {len(NIFTY_50_TICKERS)} Nifty 50 stocks... (This may take 2-3 minutes)\n")
    
    all_stock_data = []
    successful = 0
    failed = 0
    
    for idx, ticker in enumerate(NIFTY_50_TICKERS, 1):
        print(f"[{idx}/{len(NIFTY_50_TICKERS)}] Fetching {ticker}...", end=' ', flush=True)
        
        stock_data = fetch_stock_data(ticker, start_date, end_date)
        
        if stock_data:
            all_stock_data.append(stock_data)
            print(f"✓ ₹{stock_data['current_price']:.2f}")
            successful += 1
        else:
            print("✗")
            failed += 1
        
        if idx % 10 == 0:
            time.sleep(1)
    
    print(f"\n{'=' * 80}")
    print(f"Data Collection Complete: {successful} successful, {failed} failed")
    print(f"{'=' * 80}\n")
    
    if len(all_stock_data) < TOP_N_STOCKS:
        print(f"❌ Error: Not enough stocks fetched ({len(all_stock_data)}) to select top {TOP_N_STOCKS}")
        return
    
    print("🔍 Analyzing stock performance metrics...\n")
    all_metrics = []
    
    for stock_data in all_stock_data:
        metrics = analyze_stock(stock_data)
        if metrics:
            all_metrics.append(metrics)
    
    print(f"✓ Successfully analyzed {len(all_metrics)} stocks\n")
    
    if len(all_metrics) < TOP_N_STOCKS:
        print(f"❌ Error: Not enough valid stocks analyzed ({len(all_metrics)}) to select top {TOP_N_STOCKS}")
        return
    
    metrics_df = pd.DataFrame(all_metrics)
    
    metrics_df = calculate_composite_score(metrics_df)
    metrics_df = metrics_df.sort_values('composite_score', ascending=False).reset_index(drop=True)
    metrics_df['rank'] = range(1, len(metrics_df) + 1)
    
    top_stocks = metrics_df.head(TOP_N_STOCKS).copy()
    
    print("=" * 80)
    print(f"TOP {TOP_N_STOCKS} STOCKS SELECTED")
    print("=" * 80)
    for _, stock in top_stocks.iterrows():
        print(f"{int(stock['rank'])}. {stock['name']} ({stock['ticker']}) - Score: {stock['composite_score']:.2f}")
    print("=" * 80 + "\n")
    
    print(f"💰 Allocating ₹{STARTING_BUDGET:,.2f} using {ALLOCATION_METHOD.replace('_', ' ').title()} strategy...\n")
    
    if ALLOCATION_METHOD == 'equal_weight':
        allocations, total_allocated = allocate_capital_equal_weight(top_stocks, STARTING_BUDGET)
    else:
        allocations, total_allocated = allocate_capital_risk_parity(top_stocks, STARTING_BUDGET)
    
    if len(allocations) == 0:
        print("❌ Error: Failed to allocate capital")
        return
    
    allocation_dict = {alloc['ticker']: alloc for alloc in allocations}
    
    portfolio_data = []
    
    for _, stock in top_stocks.iterrows():
        ticker = stock['ticker']
        
        if ticker not in allocation_dict:
            continue
        
        allocation_data = allocation_dict[ticker]
        
        original_data = next((s for s in all_metrics if s['ticker'] == ticker), None)
        
        if original_data:
            exit_signals = calculate_exit_signals(original_data, allocation_data)
            
            portfolio_data.append({
                'Rank': int(stock['rank']),
                'Ticker': ticker.replace('.NS', ''),
                'Company Name': stock['name'],
                'Current Price': float(stock['current_price']),
                'Shares to Buy': int(allocation_data['shares']),
                'Investment Amount': float(allocation_data['allocation']),
                'Allocation %': float((allocation_data['allocation'] / total_allocated) * 100),
                'Stop-Loss Price': float(exit_signals['stop_loss_price']),
                'Take-Profit Price': float(exit_signals['take_profit_price']),
                'Potential Profit': float(exit_signals['potential_profit']),
                'Potential Loss': float(exit_signals['potential_loss']),
                'Risk/Reward': float(exit_signals['risk_reward_ratio']),
                'Exit Signal (EMA200)': exit_signals['trailing_stop_signal']
            })
    
    portfolio_df = pd.DataFrame(portfolio_data)
    
    all_stocks_df = metrics_df[[
        'rank', 'ticker', 'name', 'current_price', 'cagr', 'sharpe_ratio',
        'max_drawdown', 'volatility', 'cumulative_return', 'composite_score'
    ]].copy()
    
    all_stocks_df.columns = [
        'Rank', 'Ticker', 'Company Name', 'Current Price', 'CAGR (%)',
        'Sharpe Ratio', 'Max Drawdown (%)', 'Volatility (%)', 
        'Cumulative Return (%)', 'Composite Score'
    ]
    
    all_stocks_df['Ticker'] = all_stocks_df['Ticker'].str.replace('.NS', '')
    
    print("=" * 80)
    print("PORTFOLIO SUMMARY")
    print("=" * 80)
    print(f"Total Budget: ₹{STARTING_BUDGET:,.2f}")
    print(f"Amount Invested: ₹{total_allocated:,.2f}")
    print(f"Remaining: ₹{STARTING_BUDGET - total_allocated:,.2f}")
    print(f"Number of Stocks: {len(portfolio_df)}")
    print(f"\nTotal Potential Profit: ₹{portfolio_df['Potential Profit'].sum():,.2f}")
    print(f"Total Potential Loss: ₹{portfolio_df['Potential Loss'].sum():,.2f}")
    
    if portfolio_df['Potential Loss'].sum() > 0:
        print(f"Portfolio Risk/Reward: {portfolio_df['Potential Profit'].sum() / portfolio_df['Potential Loss'].sum():.2f}")
    
    print("=" * 80 + "\n")
    
    print("TOP 5 INVESTMENTS:")
    print("-" * 80)
    for _, row in portfolio_df.head(5).iterrows():
        print(f"{row['Rank']}. {row['Company Name']} ({row['Ticker']})")
        print(f"   Investment: ₹{row['Investment Amount']:,.2f} ({row['Allocation %']:.1f}%) - {row['Shares to Buy']} shares @ ₹{row['Current Price']:.2f}")
        print(f"   Stop-Loss: ₹{row['Stop-Loss Price']:.2f} | Take-Profit: ₹{row['Take-Profit Price']:.2f}")
        print(f"   Risk/Reward: {row['Risk/Reward']:.2f} | EMA200 Signal: {row['Exit Signal (EMA200)']}")
        print()
    
    print("\n📊 Generating Excel report...")
    create_excel_report(portfolio_df, all_stocks_df)
    
    print("\n" + "=" * 80)
    print("✅ ANALYSIS COMPLETE!")
    print("=" * 80)
    print("\n📁 Output Files:")
    print("   • nifty50_investment_plan.xlsx (Portfolio + Market Data)")
    print("\n📋 Next Steps:")
    print("   1. Review the Excel file for detailed allocation")
    print("   2. Execute trades based on 'Shares to Buy' column")
    print("   3. Set stop-loss orders at specified prices")
    print("   4. Monitor EMA200 signals for exit triggers")
    print("   5. Take profits at specified target prices")
    print("\n⚠️  DISCLAIMER:")
    print("   This is for EDUCATIONAL purposes only. Not financial advice.")
    print("   Past performance does not guarantee future results.")
    print("   Consult a SEBI-registered advisor before investing.")
    print("=" * 80 + "\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Process interrupted by user")
    except Exception as e:
        print(f"\n❌ Error occurred: {str(e)}")
        import traceback
        traceback.print_exc()
