# filename: india_stock_analyzer_advanced.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import numpy as np
import warnings
warnings.filterwarnings('ignore')

class IndianStockAnalyzer:
    def __init__(self):
        self.nse_stocks = [
            'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
            'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
            'LT.NS', 'AXISBANK.NS', 'ASIANPAINT.NS', 'MARUTI.NS', 'TITAN.NS',
            'SUNPHARMA.NS', 'ULTRACEMCO.NS', 'NESTLEIND.NS', 'BAJFINANCE.NS', 'WIPRO.NS',
            'HCLTECH.NS', 'TECHM.NS', 'POWERGRID.NS', 'NTPC.NS', 'ONGC.NS',
            'TATASTEEL.NS', 'ADANIENT.NS', 'JSWSTEEL.NS', 'GRASIM.NS', 'HINDALCO.NS',
            'DIVISLAB.NS', 'DRREDDY.NS', 'CIPLA.NS', 'EICHERMOT.NS', 'HEROMOTOCO.NS',
            'M&M.NS', 'BAJAJFINSV.NS', 'TATACONSUM.NS', 'INDUSINDBK.NS', 'COALINDIA.NS'
        ]
        self.stock_data = {}
        self.analyzed_stocks = []
        
    def fetch_stock_data(self, period='6mo'):
        print("Fetching stock data from NSE India...")
        print("=" * 70)
        
        for symbol in self.nse_stocks:
            try:
                stock = yf.Ticker(symbol)
                hist = stock.history(period=period)
                
                if not hist.empty and len(hist) > 20:
                    info = stock.info
                    company_name = info.get('longName', symbol.replace('.NS', ''))
                    
                    self.stock_data[symbol] = {
                        'history': hist,
                        'name': company_name,
                        'current_price': hist['Close'].iloc[-1],
                        'symbol': symbol
                    }
                    print(f"✓ Loaded: {company_name}")
                
            except Exception as e:
                print(f"✗ Failed: {symbol} - {str(e)}")
        
        print(f"\n✓ Successfully loaded {len(self.stock_data)} stocks")
    
    def calculate_support_resistance(self, hist):
        close_prices = hist['Close'].values
        high_prices = hist['High'].values
        low_prices = hist['Low'].values
        
        recent_high = np.max(high_prices[-20:])
        recent_low = np.min(low_prices[-20:])
        
        resistance = recent_high
        support = recent_low
        
        return support, resistance
    
    def calculate_rsi(self, prices, period=14):
        delta = prices.diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        return rsi.iloc[-1] if len(rsi) > 0 else 50
    
    def generate_investment_signals(self, hist, current_price):
        close_prices = hist['Close']
        
        sma_20 = close_prices.rolling(window=20).mean().iloc[-1]
        sma_50 = close_prices.rolling(window=min(50, len(hist))).mean().iloc[-1]
        
        support, resistance = self.calculate_support_resistance(hist)
        rsi = self.calculate_rsi(close_prices)
        
        price_range = resistance - support
        
        entry_point = support + (price_range * 0.2)
        profit_target_1 = current_price + (price_range * 0.4)
        profit_target_2 = resistance * 0.95
        stop_loss = support * 1.02
        
        distance_to_support = ((current_price - support) / support) * 100
        distance_to_resistance = ((resistance - current_price) / current_price) * 100
        
        investment_timing = "WAIT"
        timing_reason = ""
        risk_level = "MEDIUM"
        
        if current_price <= entry_point and rsi < 40:
            investment_timing = "BUY NOW"
            timing_reason = "Price near support with oversold RSI"
            risk_level = "LOW"
        elif current_price <= entry_point * 1.05 and current_price > sma_20:
            investment_timing = "BUY ON DIP"
            timing_reason = "Near entry zone, wait for small pullback"
            risk_level = "LOW-MEDIUM"
        elif distance_to_resistance < 5:
            investment_timing = "WAIT"
            timing_reason = "Price near resistance, high risk"
            risk_level = "HIGH"
        elif rsi > 70:
            investment_timing = "WAIT"
            timing_reason = "Overbought conditions, expect correction"
            risk_level = "HIGH"
        elif current_price > sma_20 and current_price < sma_50:
            investment_timing = "ACCUMULATE"
            timing_reason = "Uptrend confirmed, buy in parts"
            risk_level = "MEDIUM"
        else:
            investment_timing = "MONITOR"
            timing_reason = "No clear signal, track for entry"
            risk_level = "MEDIUM"
        
        exit_timing = []
        if current_price >= profit_target_1 * 0.95:
            exit_timing.append("BOOK 50% PROFIT - Near first target")
        if current_price >= profit_target_2 * 0.95:
            exit_timing.append("BOOK REMAINING - Near resistance")
        if rsi > 75:
            exit_timing.append("CONSIDER EXIT - Extremely overbought")
        if current_price < sma_20 and sma_20 < sma_50:
            exit_timing.append("EXIT - Trend reversal detected")
        
        if not exit_timing:
            exit_timing.append("HOLD - Target not reached")
        
        hold_duration = "2-4 weeks" if investment_timing in ["BUY NOW", "BUY ON DIP"] else "1-3 months"
        
        return {
            'entry_point': entry_point,
            'current_price': current_price,
            'stop_loss': stop_loss,
            'target_1': profit_target_1,
            'target_2': profit_target_2,
            'support': support,
            'resistance': resistance,
            'rsi': rsi,
            'investment_timing': investment_timing,
            'timing_reason': timing_reason,
            'exit_signals': exit_timing,
            'risk_level': risk_level,
            'hold_duration': hold_duration,
            'potential_gain': ((profit_target_1 - current_price) / current_price) * 100,
            'potential_loss': ((current_price - stop_loss) / current_price) * 100
        }
        
    def calculate_trend_score(self, hist):
        if len(hist) < 20:
            return 0
        
        close_prices = hist['Close']
        
        sma_20 = close_prices.rolling(window=20).mean()
        sma_50 = close_prices.rolling(window=min(50, len(hist))).mean()
        
        price_change_1w = ((close_prices.iloc[-1] - close_prices.iloc[-5]) / close_prices.iloc[-5]) * 100
        price_change_1m = ((close_prices.iloc[-1] - close_prices.iloc[-20]) / close_prices.iloc[-20]) * 100
        
        above_sma20 = 1 if close_prices.iloc[-1] > sma_20.iloc[-1] else 0
        above_sma50 = 1 if close_prices.iloc[-1] > sma_50.iloc[-1] else 0
        sma_cross = 1 if sma_20.iloc[-1] > sma_50.iloc[-1] else 0
        
        volume_trend = (hist['Volume'].iloc[-5:].mean() / hist['Volume'].iloc[-20:-5].mean()) if len(hist) >= 20 else 1
        volume_score = min(volume_trend, 2)
        
        rsi = self.calculate_rsi(close_prices)
        rsi_score = 0
        if 40 < rsi < 70:
            rsi_score = 1
        elif rsi >= 70:
            rsi_score = 0.5
        
        trend_score = (
            price_change_1w * 0.3 +
            price_change_1m * 0.2 +
            above_sma20 * 10 +
            above_sma50 * 10 +
            sma_cross * 15 +
            volume_score * 5 +
            rsi_score * 10
        )
        
        return trend_score
    
    def analyze_stocks(self):
        print("\nAnalyzing stock trends and generating signals...")
        print("=" * 70)
        
        for symbol, data in self.stock_data.items():
            hist = data['history']
            trend_score = self.calculate_trend_score(hist)
            
            close_prices = hist['Close']
            price_change_1w = ((close_prices.iloc[-1] - close_prices.iloc[-5]) / close_prices.iloc[-5]) * 100
            price_change_1m = ((close_prices.iloc[-1] - close_prices.iloc[-20]) / close_prices.iloc[-20]) * 100
            
            signals = self.generate_investment_signals(hist, data['current_price'])
            
            self.analyzed_stocks.append({
                'symbol': symbol,
                'name': data['name'],
                'current_price': data['current_price'],
                'change_1w': price_change_1w,
                'change_1m': price_change_1m,
                'trend_score': trend_score,
                'history': hist,
                'signals': signals
            })
        
        self.analyzed_stocks.sort(key=lambda x: x['trend_score'], reverse=True)
        
        print("\n" + "="*70)
        print("TOP 10 STOCKS WITH UPWARD MOMENTUM & INVESTMENT SIGNALS")
        print("="*70 + "\n")
        
        for i, stock in enumerate(self.analyzed_stocks[:10], 1):
            signals = stock['signals']
            print(f"\n{i}. {stock['name']}")
            print(f"   Symbol: {stock['symbol']}")
            print(f"   Current Price: ₹{stock['current_price']:.2f}")
            print(f"   Trend Score: {stock['trend_score']:.2f}")
            print(f"   1 Week: {stock['change_1w']:+.2f}% | 1 Month: {stock['change_1m']:+.2f}%")
            print(f"\n   📊 TECHNICAL LEVELS:")
            print(f"   Support: ₹{signals['support']:.2f} | Resistance: ₹{signals['resistance']:.2f}")
            print(f"   RSI: {signals['rsi']:.1f}")
            print(f"\n   💰 INVESTMENT RECOMMENDATION:")
            print(f"   Action: {signals['investment_timing']} ({signals['risk_level']} Risk)")
            print(f"   Reason: {signals['timing_reason']}")
            print(f"   Hold Duration: {signals['hold_duration']}")
            print(f"\n   🎯 ENTRY & EXIT STRATEGY:")
            print(f"   Entry Point: ₹{signals['entry_point']:.2f}")
            print(f"   Stop Loss: ₹{signals['stop_loss']:.2f} ({signals['potential_loss']:.1f}% risk)")
            print(f"   Target 1: ₹{signals['target_1']:.2f} ({signals['potential_gain']:.1f}% gain)")
            print(f"   Target 2: ₹{signals['target_2']:.2f}")
            print(f"\n   🚪 EXIT SIGNALS:")
            for exit_signal in signals['exit_signals']:
                print(f"   • {exit_signal}")
            print(f"\n   {'-'*70}")
    
    def plot_top_stocks(self, top_n=10):
        top_stocks = self.analyzed_stocks[:top_n]
        
        fig = plt.figure(figsize=(20, 16))
        fig.suptitle('Top 10 Indian Stocks - Trend Analysis & Investment Signals', 
                     fontsize=20, fontweight='bold', y=0.997)
        
        for idx, stock in enumerate(top_stocks, 1):
            ax = plt.subplot(4, 3, idx)
            hist = stock['history']
            signals = stock['signals']
            
            ax.plot(hist.index, hist['Close'], color='#00A3E0', linewidth=2.5, label='Close Price')
            
            sma_20 = hist['Close'].rolling(window=20).mean()
            sma_50 = hist['Close'].rolling(window=min(50, len(hist))).mean()
            ax.plot(hist.index, sma_20, color='#86BC25', linewidth=1.5, 
                   linestyle='--', label='SMA 20', alpha=0.8)
            ax.plot(hist.index, sma_50, color='#DA291C', linewidth=1.5, 
                   linestyle='--', label='SMA 50', alpha=0.8)
            
            ax.axhline(y=signals['support'], color='#FF6B6B', linestyle=':', 
                      linewidth=2, label='Support', alpha=0.7)
            ax.axhline(y=signals['resistance'], color='#4ECDC4', linestyle=':', 
                      linewidth=2, label='Resistance', alpha=0.7)
            ax.axhline(y=signals['entry_point'], color='#86BC25', linestyle='-.', 
                      linewidth=1.5, label='Entry Point', alpha=0.6)
            
            ax.fill_between(hist.index, hist['Close'], alpha=0.1, color='#00A3E0')
            
            timing_emoji = {
                'BUY NOW': '🟢',
                'BUY ON DIP': '🟡',
                'ACCUMULATE': '🔵',
                'WAIT': '🔴',
                'MONITOR': '⚪'
            }
            emoji = timing_emoji.get(signals['investment_timing'], '⚪')
            
            ax.set_title(f"{idx}. {stock['name']} {emoji}\n"
                        f"₹{stock['current_price']:.2f} | {signals['investment_timing']} | "
                        f"Target: ₹{signals['target_1']:.2f} (+{signals['potential_gain']:.1f}%)",
                        fontsize=9, fontweight='bold', pad=8)
            
            ax.set_xlabel('Date', fontsize=8, fontweight='600')
            ax.set_ylabel('Price (₹)', fontsize=8, fontweight='600')
            ax.legend(loc='upper left', fontsize=7, framealpha=0.9, ncol=2)
            ax.grid(True, alpha=0.2, linestyle=':')
            
            for spine in ax.spines.values():
                spine.set_color('#E6E6E6')
            
            ax.tick_params(labelsize=7)
        
        if len(top_stocks) == 10:
            ax_summary = plt.subplot(4, 3, 11)
            ax_summary.axis('off')
            
            buy_now = sum(1 for s in top_stocks if s['signals']['investment_timing'] == 'BUY NOW')
            buy_dip = sum(1 for s in top_stocks if s['signals']['investment_timing'] == 'BUY ON DIP')
            accumulate = sum(1 for s in top_stocks if s['signals']['investment_timing'] == 'ACCUMULATE')
            wait = sum(1 for s in top_stocks if s['signals']['investment_timing'] in ['WAIT', 'MONITOR'])
            
            summary_text = "INVESTMENT SUMMARY\n"
            summary_text += "="*30 + "\n\n"
            summary_text += f"🟢 BUY NOW: {buy_now} stocks\n"
            summary_text += f"🟡 BUY ON DIP: {buy_dip} stocks\n"
            summary_text += f"🔵 ACCUMULATE: {accumulate} stocks\n"
            summary_text += f"⚪ WAIT/MONITOR: {wait} stocks\n\n"
            summary_text += "="*30 + "\n"
            summary_text += "LEGEND:\n"
            summary_text += "• Green line: SMA 20\n"
            summary_text += "• Red line: SMA 50\n"
            summary_text += "• Dotted: Support/Resistance\n\n"
            summary_text += "⚠️ DISCLAIMER:\n"
            summary_text += "Educational purpose only.\n"
            summary_text += "Not financial advice.\n"
            summary_text += "Consult advisor before\n"
            summary_text += "investing."
            
            ax_summary.text(0.05, 0.95, summary_text, 
                          transform=ax_summary.transAxes,
                          fontsize=8, verticalalignment='top',
                          fontfamily='monospace',
                          bbox=dict(boxstyle='round', facecolor='#F5F5F5', 
                                  edgecolor='#86BC25', linewidth=2, pad=12))
            
            ax_legend = plt.subplot(4, 3, 12)
            ax_legend.axis('off')
            
            best_stock = top_stocks[0]
            legend_text = "TOP PICK DETAILS\n"
            legend_text += "="*30 + "\n\n"
            legend_text += f"{best_stock['name']}\n"
            legend_text += f"({best_stock['symbol'].replace('.NS', '')})\n\n"
            legend_text += f"Price: ₹{best_stock['current_price']:.2f}\n"
            legend_text += f"Action: {best_stock['signals']['investment_timing']}\n"
            legend_text += f"Entry: ₹{best_stock['signals']['entry_point']:.2f}\n"
            legend_text += f"Target: ₹{best_stock['signals']['target_1']:.2f}\n"
            legend_text += f"Stop Loss: ₹{best_stock['signals']['stop_loss']:.2f}\n"
            legend_text += f"Potential: +{best_stock['signals']['potential_gain']:.1f}%\n"
            legend_text += f"Risk: -{best_stock['signals']['potential_loss']:.1f}%\n"
            legend_text += f"Hold: {best_stock['signals']['hold_duration']}\n\n"
            legend_text += f"RSI: {best_stock['signals']['rsi']:.1f}\n"
            legend_text += f"Risk Level: {best_stock['signals']['risk_level']}"
            
            ax_legend.text(0.05, 0.95, legend_text, 
                          transform=ax_legend.transAxes,
                          fontsize=8, verticalalignment='top',
                          fontfamily='monospace',
                          bbox=dict(boxstyle='round', facecolor='#E8F5E9', 
                                  edgecolor='#86BC25', linewidth=2, pad=12))
        
        plt.tight_layout()
        plt.subplots_adjust(top=0.98, hspace=0.4, wspace=0.3)
        plt.show()
    
    def save_detailed_report(self, filename='stock_investment_report.csv'):
        report_data = []
        for stock in self.analyzed_stocks[:10]:
            signals = stock['signals']
            report_data.append({
                'Symbol': stock['symbol'],
                'Company Name': stock['name'],
                'Current Price (₹)': round(stock['current_price'], 2),
                '1W Change (%)': round(stock['change_1w'], 2),
                '1M Change (%)': round(stock['change_1m'], 2),
                'Trend Score': round(stock['trend_score'], 2),
                'Investment Action': signals['investment_timing'],
                'Risk Level': signals['risk_level'],
                'Entry Point (₹)': round(signals['entry_point'], 2),
                'Stop Loss (₹)': round(signals['stop_loss'], 2),
                'Target 1 (₹)': round(signals['target_1'], 2),
                'Target 2 (₹)': round(signals['target_2'], 2),
                'Potential Gain (%)': round(signals['potential_gain'], 2),
                'Potential Loss (%)': round(signals['potential_loss'], 2),
                'RSI': round(signals['rsi'], 1),
                'Hold Duration': signals['hold_duration'],
                'Reason': signals['timing_reason']
            })
        
        df = pd.DataFrame(report_data)
        df.to_csv(filename, index=False)
        print(f"\n✓ Detailed investment report saved to {filename}")

def main():
    print("\n" + "="*70)
    print("   INDIAN STOCK MARKET ANALYZER PRO")
    print("   NSE Top 10 Stocks with Buy/Sell Timing Recommendations")
    print("="*70 + "\n")
    
    analyzer = IndianStockAnalyzer()
    
    analyzer.fetch_stock_data(period='6mo')
    
    analyzer.analyze_stocks()
    
    print("\n\nGenerating detailed charts with entry/exit points...")
    analyzer.plot_top_stocks(top_n=10)
    
    save_option = input("\nDo you want to save the detailed investment report to CSV? (y/n): ").strip().lower()
    if save_option == 'y':
        analyzer.save_detailed_report()
    
    print("\n" + "="*70)
    print("⚠️  IMPORTANT DISCLAIMER:")
    print("This analysis is for educational purposes only and should not be")
    print("considered as financial advice. Always consult with a certified")
    print("financial advisor before making investment decisions.")
    print("Past performance does not guarantee future results.")
    print("="*70 + "\n")

if __name__ == '__main__':
    main()


#pip install yfinance pandas matplotlib