# filename: stock_2year_analyzer_complete.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import numpy as np
import warnings
import time
import os
warnings.filterwarnings('ignore')

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils.dataframe import dataframe_to_rows
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False
    print("⚠️  Installing openpyxl for Excel formatting...")
    os.system('pip install openpyxl')
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils.dataframe import dataframe_to_rows
        OPENPYXL_AVAILABLE = True
    except:
        OPENPYXL_AVAILABLE = False

class TwoYearStockAnalyzer:
    def __init__(self, investment_capital=100000):
        # Comprehensive list of quality NSE stocks
        self.nse_stocks = [
            # Large Cap Blue Chips
            'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
            'HINDUNILVR.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'KOTAKBANK.NS',
            
            # IT & Technology
            'WIPRO.NS', 'HCLTECH.NS', 'TECHM.NS', 'LTI.NS', 'PERSISTENT.NS',
            'MPHASIS.NS', 'COFORGE.NS', 'LTTS.NS', 'TATAELXSI.NS',
            
            # Banking & Finance
            'AXISBANK.NS', 'INDUSINDBK.NS', 'FEDERALBNK.NS', 'BANDHANBNK.NS',
            'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'ICICIPRULI.NS',
            
            # Pharma & Healthcare
            'SUNPHARMA.NS', 'DRREDDY.NS', 'CIPLA.NS', 'DIVISLAB.NS', 'LUPIN.NS',
            'BIOCON.NS', 'TORNTPHARM.NS', 'AUROPHARMA.NS', 'ALKEM.NS',
            
            # Auto & Components
            'MARUTI.NS', 'M&M.NS', 'TATAMOTORS.NS', 'BAJAJ-AUTO.NS', 'EICHERMOT.NS',
            'HEROMOTOCO.NS', 'ESCORTS.NS', 'MOTHERSON.NS', 'BALKRISIND.NS',
            
            # Metals & Mining
            'TATASTEEL.NS', 'JSWSTEEL.NS', 'HINDALCO.NS', 'VEDL.NS', 'SAIL.NS',
            'NMDC.NS', 'COALINDIA.NS', 'HINDZINC.NS', 'JINDALSTEL.NS',
            
            # Energy & Power
            'NTPC.NS', 'POWERGRID.NS', 'ADANIGREEN.NS', 'ADANIPOWER.NS', 'TATAPOWER.NS',
            'NHPC.NS', 'RECLTD.NS', 'PFC.NS', 'GAIL.NS', 'IOC.NS', 'BPCL.NS', 'ONGC.NS',
            
            # Infrastructure
            'LT.NS', 'ULTRACEMCO.NS', 'AMBUJACEM.NS', 'ACC.NS', 'GRASIM.NS',
            'IRCTC.NS', 'IRFC.NS', 'RVNL.NS', 'BEL.NS', 'HAL.NS',
            
            # Consumer Goods
            'NESTLEIND.NS', 'BRITANNIA.NS', 'DABUR.NS', 'MARICO.NS', 'GODREJCP.NS',
            'COLPAL.NS', 'TATACONSUM.NS', 'VBL.NS',
            
            # Real Estate
            'DLF.NS', 'GODREJPROP.NS', 'OBEROIRLTY.NS', 'PRESTIGE.NS', 'BRIGADE.NS',
            'PHOENIXLTD.NS', 'SOBHA.NS',
            
            # Retail & E-commerce
            'TITAN.NS', 'DMART.NS', 'JUBLFOOD.NS', 'TRENT.NS',
            'PAGEIND.NS', 'ZOMATO.NS', 'NYKAA.NS',
            
            # Specialty & Others
            'ASIANPAINT.NS', 'BERGEPAINT.NS', 'PIDILITIND.NS', 'VOLTAS.NS', 'HAVELLS.NS',
            'CROMPTON.NS', 'WHIRLPOOL.NS', 'BATAINDIA.NS'
        ]
        
        self.investment_capital = max(investment_capital, 10000)
        self.stock_data = {}
        self.analyzed_stocks = []
        self.today = datetime.now()
        self.two_years_ago = self.today - timedelta(days=730)
        self.output_folder = f"stock_analysis_2year_{self.today.strftime('%Y%m%d_%H%M')}"
        
        if not os.path.exists(self.output_folder):
            os.makedirs(self.output_folder)
    
    def get_current_price(self, stock, hist):
        """Robust method to get current price with multiple fallback options"""
        current_price = None
        
        try:
            if not hist.empty and len(hist) > 0:
                last_close = hist['Close'].iloc[-1]
                if pd.notna(last_close) and last_close > 0:
                    current_price = float(last_close)
                    return current_price
        except Exception as e:
            pass
        
        try:
            info = stock.info
            if 'currentPrice' in info and info['currentPrice'] is not None:
                price = info['currentPrice']
                if price > 0:
                    current_price = float(price)
                    return current_price
        except Exception as e:
            pass
        
        try:
            info = stock.info
            if 'regularMarketPrice' in info and info['regularMarketPrice'] is not None:
                price = info['regularMarketPrice']
                if price > 0:
                    current_price = float(price)
                    return current_price
        except Exception as e:
            pass
        
        try:
            if hasattr(stock, 'fast_info') and hasattr(stock.fast_info, 'last_price'):
                price = stock.fast_info.last_price
                if pd.notna(price) and price > 0:
                    current_price = float(price)
                    return current_price
        except Exception as e:
            pass
        
        try:
            today_data = stock.history(period='1d')
            if not today_data.empty and len(today_data) > 0:
                price = today_data['Close'].iloc[-1]
                if pd.notna(price) and price > 0:
                    current_price = float(price)
                    return current_price
        except Exception as e:
            pass
        
        try:
            recent_data = stock.history(period='5d')
            if not recent_data.empty and len(recent_data) > 0:
                close_prices = recent_data['Close'].dropna()
                if len(close_prices) > 0:
                    price = close_prices.iloc[-1]
                    if price > 0:
                        current_price = float(price)
                        return current_price
        except Exception as e:
            pass
        
        return current_price
    
    def fetch_2year_data(self):
        print(f"Fetching 2-YEAR historical data from {len(self.nse_stocks)} NSE stocks...")
        print(f"Period: {self.two_years_ago.strftime('%Y-%m-%d')} to {self.today.strftime('%Y-%m-%d')}")
        print(f"Analysis timestamp: {self.today.strftime('%Y-%m-%d %H:%M:%S IST')}")
        print("=" * 80)
        print("This will take 3-5 minutes for comprehensive analysis...")
        print("=" * 80 + "\n")
        
        successful = 0
        failed = 0
        
        for idx, symbol in enumerate(self.nse_stocks, 1):
            try:
                print(f"[{idx}/{len(self.nse_stocks)}] {symbol}...", end=' ', flush=True)
                
                stock = yf.Ticker(symbol)
                
                hist = None
                for attempt in range(3):
                    try:
                        hist = stock.history(start=self.two_years_ago, end=self.today)
                        if not hist.empty and len(hist) >= 200:
                            break
                        time.sleep(0.5)
                    except:
                        time.sleep(1)
                
                if hist is None or hist.empty or len(hist) < 200:
                    print(f"✗ Insufficient data ({len(hist) if hist is not None else 0} days)")
                    failed += 1
                    continue
                
                current_price = self.get_current_price(stock, hist)
                
                if current_price is None or current_price <= 0:
                    print(f"✗ Invalid price (could not fetch)")
                    failed += 1
                    continue
                
                try:
                    info = stock.info
                    company_name = info.get('longName', info.get('shortName', symbol.replace('.NS', '')))
                    market_cap = info.get('marketCap', 0)
                    sector = info.get('sector', 'Unknown')
                    industry = info.get('industry', 'Unknown')
                except:
                    company_name = symbol.replace('.NS', '')
                    market_cap = 0
                    sector = 'Unknown'
                    industry = 'Unknown'
                
                avg_volume = hist['Volume'].mean()
                
                if pd.isna(avg_volume) or avg_volume < 10000:
                    print(f"✗ Low liquidity")
                    failed += 1
                    continue
                
                self.stock_data[symbol] = {
                    'history': hist,
                    'name': company_name,
                    'current_price': float(current_price),
                    'symbol': symbol,
                    'market_cap': market_cap,
                    'sector': sector,
                    'industry': industry,
                    'avg_volume': float(avg_volume),
                    'data_points': len(hist),
                    'last_update': self.today
                }
                
                print(f"✓ ₹{current_price:.2f} ({len(hist)} days)")
                successful += 1
                
                if idx % 10 == 0:
                    time.sleep(1)
                
            except Exception as e:
                print(f"✗ Error: {str(e)[:40]}")
                failed += 1
                time.sleep(0.5)
        
        print(f"\n{'='*80}")
        print(f"DATA COLLECTION COMPLETE")
        print(f"{'='*80}")
        print(f"✓ Successfully loaded: {successful} stocks")
        print(f"✗ Failed/filtered: {failed} stocks")
        print(f"Total for deep analysis: {len(self.stock_data)}")
        if self.stock_data:
            print(f"Average data points: {np.mean([s['data_points'] for s in self.stock_data.values()]):.0f} days")
        print(f"{'='*80}\n")
    
    def calculate_performance_metrics(self, hist, current_price):
        """Calculate historical performance over different periods"""
        try:
            metrics = {}
            
            if hist.empty or len(hist) < 50:
                return None
            
            close_prices = hist['Close'].dropna()
            
            if len(close_prices) < 50:
                return None
            
            if len(close_prices) >= 480:
                price_2y_ago = close_prices.iloc[0]
                if price_2y_ago > 0:
                    metrics['return_2y'] = ((current_price - price_2y_ago) / price_2y_ago) * 100
                else:
                    metrics['return_2y'] = 0
            else:
                metrics['return_2y'] = 0
            
            if len(close_prices) >= 252:
                price_1y_ago = close_prices.iloc[-252]
                if price_1y_ago > 0:
                    metrics['return_1y'] = ((current_price - price_1y_ago) / price_1y_ago) * 100
                else:
                    metrics['return_1y'] = 0
            else:
                metrics['return_1y'] = 0
            
            if len(close_prices) >= 126:
                price_6m_ago = close_prices.iloc[-126]
                if price_6m_ago > 0:
                    metrics['return_6m'] = ((current_price - price_6m_ago) / price_6m_ago) * 100
                else:
                    metrics['return_6m'] = 0
            else:
                metrics['return_6m'] = 0
            
            if len(close_prices) >= 63:
                price_3m_ago = close_prices.iloc[-63]
                if price_3m_ago > 0:
                    metrics['return_3m'] = ((current_price - price_3m_ago) / price_3m_ago) * 100
                else:
                    metrics['return_3m'] = 0
            else:
                metrics['return_3m'] = 0
            
            if len(close_prices) >= 21:
                price_1m_ago = close_prices.iloc[-21]
                if price_1m_ago > 0:
                    metrics['return_1m'] = ((current_price - price_1m_ago) / price_1m_ago) * 100
                else:
                    metrics['return_1m'] = 0
            else:
                metrics['return_1m'] = 0
            
            if len(close_prices) >= 252:
                years = len(close_prices) / 252
                start_price = close_prices.iloc[0]
                if start_price > 0 and years > 0:
                    metrics['cagr'] = (((current_price / start_price) ** (1/years)) - 1) * 100
                else:
                    metrics['cagr'] = 0
            else:
                metrics['cagr'] = 0
            
            daily_returns = close_prices.pct_change().dropna()
            if len(daily_returns) > 0:
                std_dev = daily_returns.std()
                if pd.notna(std_dev):
                    metrics['volatility'] = float(std_dev * np.sqrt(252) * 100)
                else:
                    metrics['volatility'] = 0
            else:
                metrics['volatility'] = 0
            
            risk_free_rate = 6.0
            if metrics['volatility'] > 0:
                metrics['sharpe_ratio'] = (metrics['cagr'] - risk_free_rate) / metrics['volatility']
            else:
                metrics['sharpe_ratio'] = 0
            
            if len(daily_returns) > 0:
                cumulative = (1 + daily_returns).cumprod()
                running_max = cumulative.expanding().max()
                drawdown = (cumulative - running_max) / running_max
                max_dd = drawdown.min()
                if pd.notna(max_dd):
                    metrics['max_drawdown'] = float(max_dd * 100)
                else:
                    metrics['max_drawdown'] = -10
            else:
                metrics['max_drawdown'] = -10
            
            if len(daily_returns) > 0:
                metrics['win_rate'] = float((daily_returns > 0).sum() / len(daily_returns) * 100)
            else:
                metrics['win_rate'] = 50
            
            if len(daily_returns) > 0:
                gains = daily_returns[daily_returns > 0]
                losses = daily_returns[daily_returns < 0]
                if len(gains) > 0 and len(losses) > 0:
                    avg_gain = gains.mean() * 100
                    avg_loss = abs(losses.mean() * 100)
                    if avg_loss > 0:
                        metrics['gain_loss_ratio'] = avg_gain / avg_loss
                    else:
                        metrics['gain_loss_ratio'] = 1
                else:
                    metrics['gain_loss_ratio'] = 1
            else:
                metrics['gain_loss_ratio'] = 1
            
            for key in metrics:
                if pd.isna(metrics[key]) or np.isinf(metrics[key]):
                    metrics[key] = 0
            
            return metrics
        except Exception as e:
            return None
    
    def calculate_technical_indicators(self, hist):
        """Calculate comprehensive technical indicators"""
        try:
            close = hist['Close'].dropna()
            high = hist['High'].dropna()
            low = hist['Low'].dropna()
            volume = hist['Volume'].dropna()
            
            if len(close) < 50:
                return None
            
            indicators = {}
            
            indicators['sma_20'] = float(close.rolling(window=20).mean().iloc[-1])
            indicators['sma_50'] = float(close.rolling(window=50).mean().iloc[-1])
            
            if len(close) >= 100:
                indicators['sma_100'] = float(close.rolling(window=100).mean().iloc[-1])
            else:
                indicators['sma_100'] = indicators['sma_50']
            
            if len(close) >= 200:
                indicators['sma_200'] = float(close.rolling(window=200).mean().iloc[-1])
            else:
                indicators['sma_200'] = indicators['sma_100']
            
            indicators['ema_12'] = float(close.ewm(span=12, adjust=False).mean().iloc[-1])
            indicators['ema_26'] = float(close.ewm(span=26, adjust=False).mean().iloc[-1])
            
            delta = close.diff()
            gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
            loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
            rs = gain / loss
            rsi = 100 - (100 / (1 + rs))
            rsi_val = rsi.iloc[-1]
            if pd.notna(rsi_val) and not np.isinf(rsi_val):
                indicators['rsi'] = float(max(0, min(100, rsi_val)))
            else:
                indicators['rsi'] = 50
            
            macd_line = indicators['ema_12'] - indicators['ema_26']
            signal_line = close.ewm(span=9, adjust=False).mean().iloc[-1]
            indicators['macd'] = float(macd_line)
            indicators['macd_signal'] = float(signal_line)
            indicators['macd_histogram'] = indicators['macd'] - indicators['macd_signal']
            
            if len(high) >= 28 and len(low) >= 28:
                plus_dm = high.diff()
                minus_dm = -low.diff()
                plus_dm[plus_dm < 0] = 0
                minus_dm[minus_dm < 0] = 0
                
                tr1 = high - low
                tr2 = abs(high - close.shift())
                tr3 = abs(low - close.shift())
                tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
                atr = tr.rolling(window=14).mean()
                
                plus_di = 100 * (plus_dm.rolling(window=14).mean() / atr)
                minus_di = 100 * (minus_dm.rolling(window=14).mean() / atr)
                dx = 100 * abs(plus_di - minus_di) / (plus_di + minus_di + 0.0001)
                adx = dx.rolling(window=14).mean()
                adx_val = adx.iloc[-1]
                if pd.notna(adx_val) and not np.isinf(adx_val):
                    indicators['adx'] = float(max(0, min(100, adx_val)))
                else:
                    indicators['adx'] = 25
            else:
                indicators['adx'] = 25
            
            sma_20 = close.rolling(window=20).mean()
            std_20 = close.rolling(window=20).std()
            indicators['bb_upper'] = float((sma_20 + (std_20 * 2)).iloc[-1])
            indicators['bb_middle'] = float(sma_20.iloc[-1])
            indicators['bb_lower'] = float((sma_20 - (std_20 * 2)).iloc[-1])
            if indicators['bb_middle'] > 0:
                indicators['bb_width'] = float(((indicators['bb_upper'] - indicators['bb_lower']) / indicators['bb_middle']) * 100)
            else:
                indicators['bb_width'] = 10
            
            indicators['volume_sma_20'] = float(volume.rolling(window=20).mean().iloc[-1])
            if indicators['volume_sma_20'] > 0:
                recent_vol = volume.iloc[-5:].mean()
                indicators['volume_ratio'] = float(recent_vol / indicators['volume_sma_20'])
            else:
                indicators['volume_ratio'] = 1.0
            
            if len(low) >= 252:
                indicators['support_52w'] = float(low.iloc[-252:].min())
            else:
                indicators['support_52w'] = float(low.min())
            
            if len(high) >= 252:
                indicators['resistance_52w'] = float(high.iloc[-252:].max())
            else:
                indicators['resistance_52w'] = float(high.max())
            
            for key in indicators:
                if pd.isna(indicators[key]) or np.isinf(indicators[key]):
                    if 'ratio' in key:
                        indicators[key] = 1.0
                    elif 'rsi' in key:
                        indicators[key] = 50.0
                    else:
                        indicators[key] = 0.0
            
            return indicators
        except Exception as e:
            return None
    
    def calculate_quality_score(self, stock_data, performance, indicators):
        """Calculate comprehensive quality score (0-100)"""
        try:
            score = 0
            signals = []
            
            current_price = stock_data['current_price']
            
            perf_score = 0
            
            if performance['return_2y'] > 100:
                perf_score += 10
                signals.append("Exceptional 2Y growth >100%")
            elif performance['return_2y'] > 50:
                perf_score += 8
                signals.append("Strong 2Y growth >50%")
            elif performance['return_2y'] > 20:
                perf_score += 6
                signals.append("Good 2Y growth >20%")
            elif performance['return_2y'] > 0:
                perf_score += 4
            
            if performance['return_1y'] > 50:
                perf_score += 10
                signals.append("Excellent 1Y return >50%")
            elif performance['return_1y'] > 30:
                perf_score += 8
                signals.append("Strong 1Y return >30%")
            elif performance['return_1y'] > 15:
                perf_score += 6
            elif performance['return_1y'] > 0:
                perf_score += 4
            
            if performance['return_3m'] > 15 and performance['return_1m'] > 5:
                perf_score += 10
                signals.append("Strong recent momentum")
            elif performance['return_3m'] > 10:
                perf_score += 6
            elif performance['return_3m'] > 0:
                perf_score += 3
            
            if performance['cagr'] > 25:
                perf_score += 10
                signals.append(f"Outstanding CAGR {performance['cagr']:.1f}%")
            elif performance['cagr'] > 15:
                perf_score += 7
            elif performance['cagr'] > 10:
                perf_score += 5
            
            score += perf_score
            
            tech_score = 0
            
            if current_price > indicators['sma_20'] > indicators['sma_50'] > indicators['sma_200']:
                tech_score += 10
                signals.append("Strong uptrend - All MAs aligned")
            elif current_price > indicators['sma_50'] > indicators['sma_200']:
                tech_score += 7
                signals.append("Uptrend - Price above key MAs")
            elif current_price > indicators['sma_200']:
                tech_score += 5
            
            if 40 < indicators['rsi'] < 70:
                tech_score += 5
                signals.append("Healthy RSI - Room to grow")
            elif 30 < indicators['rsi'] < 40:
                tech_score += 4
                signals.append("Oversold - Reversal opportunity")
            elif indicators['rsi'] < 30:
                tech_score += 3
            
            if indicators['macd'] > indicators['macd_signal'] and indicators['macd_histogram'] > 0:
                tech_score += 5
                signals.append("Bullish MACD crossover")
            elif indicators['macd'] > indicators['macd_signal']:
                tech_score += 3
            
            if indicators['adx'] > 25:
                tech_score += 5
                signals.append(f"Strong trend (ADX {indicators['adx']:.0f})")
            elif indicators['adx'] > 20:
                tech_score += 3
            
            if indicators['volume_ratio'] > 1.5:
                tech_score += 5
                signals.append("Volume surge detected")
            elif indicators['volume_ratio'] > 1.2:
                tech_score += 3
            
            score += tech_score
            
            risk_score = 0
            
            if performance['sharpe_ratio'] > 1.5:
                risk_score += 10
                signals.append("Excellent risk-adjusted returns")
            elif performance['sharpe_ratio'] > 1.0:
                risk_score += 7
            elif performance['sharpe_ratio'] > 0.5:
                risk_score += 5
            
            if performance['max_drawdown'] > -20:
                risk_score += 5
                signals.append("Low drawdown - Stable stock")
            elif performance['max_drawdown'] > -30:
                risk_score += 3
            
            if performance['win_rate'] > 55:
                risk_score += 5
            elif performance['win_rate'] > 52:
                risk_score += 3
            
            score += risk_score
            
            consistency_score = 0
            
            positive_periods = sum([
                performance['return_2y'] > 0,
                performance['return_1y'] > 0,
                performance['return_6m'] > 0,
                performance['return_3m'] > 0
            ])
            
            if positive_periods == 4:
                consistency_score += 10
                signals.append("Consistent growth across all periods")
            elif positive_periods == 3:
                consistency_score += 7
            elif positive_periods >= 2:
                consistency_score += 4
            
            score += consistency_score
            
            final_score = min(score, 100)
            
            if final_score >= 80:
                rating = "EXCELLENT"
                confidence = 90 + (final_score - 80) / 2
            elif final_score >= 70:
                rating = "VERY GOOD"
                confidence = 80 + (final_score - 70)
            elif final_score >= 60:
                rating = "GOOD"
                confidence = 70 + (final_score - 60)
            elif final_score >= 50:
                rating = "MODERATE"
                confidence = 60 + (final_score - 50)
            else:
                rating = "FAIR"
                confidence = 50 + (final_score / 2)
            
            return {
                'quality_score': int(final_score),
                'rating': rating,
                'confidence': round(confidence, 1),
                'signals': signals[:8],
                'performance_contribution': perf_score,
                'technical_contribution': tech_score,
                'risk_contribution': risk_score,
                'consistency_contribution': consistency_score
            }
        except Exception as e:
            return None
    
    def analyze_all_stocks(self):
        if not self.stock_data:
            print("⚠️  No stock data available for analysis.")
            self.top_20_stocks = []
            return
        
        print(f"Performing deep analysis on {len(self.stock_data)} stocks...")
        print("Calculating: Performance metrics, Technical indicators, Quality scores")
        print("=" * 80 + "\n")
        
        analysis_count = 0
        
        for symbol, data in self.stock_data.items():
            try:
                hist = data['history']
                current_price = data['current_price']
                
                performance = self.calculate_performance_metrics(hist, current_price)
                if performance is None:
                    continue
                
                indicators = self.calculate_technical_indicators(hist)
                if indicators is None:
                    continue
                
                quality = self.calculate_quality_score(data, performance, indicators)
                if quality is None:
                    continue
                
                target_30d = current_price * (1 + max(performance['return_1m'], 3) / 100 * 1.5)
                target_90d = current_price * (1 + max(performance['return_3m'], 8) / 100 * 1.2)
                stop_loss = max(indicators['support_52w'] * 1.02, current_price * 0.92)
                
                potential_gain_30d = ((target_30d - current_price) / current_price) * 100
                potential_gain_90d = ((target_90d - current_price) / current_price) * 100
                
                self.analyzed_stocks.append({
                    'symbol': symbol,
                    'name': data['name'],
                    'sector': data['sector'],
                    'industry': data['industry'],
                    'current_price': current_price,
                    'market_cap': data['market_cap'],
                    'history': hist,
                    'performance': performance,
                    'indicators': indicators,
                    'quality': quality,
                    'target_30d': float(target_30d),
                    'target_90d': float(target_90d),
                    'stop_loss': float(stop_loss),
                    'potential_gain_30d': float(potential_gain_30d),
                    'potential_gain_90d': float(potential_gain_90d)
                })
                
                analysis_count += 1
                if analysis_count % 10 == 0:
                    print(f"Analyzed {analysis_count}/{len(self.stock_data)} stocks...")
                
            except Exception as e:
                continue
        
        if not self.analyzed_stocks:
            print("\n⚠️  Failed to analyze any stocks.")
            self.top_20_stocks = []
            return
        
        self.analyzed_stocks.sort(key=lambda x: x['quality']['quality_score'], reverse=True)
        
        print(f"\n{'='*80}")
        print(f"ANALYSIS COMPLETE")
        print(f"{'='*80}")
        print(f"Total stocks analyzed: {len(self.analyzed_stocks)}")
        
        excellent = len([s for s in self.analyzed_stocks if s['quality']['rating'] == 'EXCELLENT'])
        very_good = len([s for s in self.analyzed_stocks if s['quality']['rating'] == 'VERY GOOD'])
        good = len([s for s in self.analyzed_stocks if s['quality']['rating'] == 'GOOD'])
        
        print(f"\nRating Distribution:")
        print(f"  EXCELLENT (80+): {excellent}")
        print(f"  VERY GOOD (70-79): {very_good}")
        print(f"  GOOD (60-69): {good}")
        print(f"  Others: {len(self.analyzed_stocks) - excellent - very_good - good}")
        
        self.top_20_stocks = self.analyzed_stocks[:min(20, len(self.analyzed_stocks))]
        
        print(f"\n✓ Selected TOP {len(self.top_20_stocks)} stocks for investment")
        print(f"{'='*80}\n")
        
        self.allocate_capital_top20()
    
    def allocate_capital_top20(self):
        """Allocate 100% capital across top 20 stocks"""
        try:
            if not self.top_20_stocks:
                print("⚠️  No stocks to allocate capital to.")
                return
            
            print(f"{'='*80}")
            print("CAPITAL ALLOCATION - TOP 20 STOCKS")
            print(f"{'='*80}\n")
            
            weights = []
            for stock in self.top_20_stocks:
                quality_score = stock['quality']['quality_score']
                cagr = stock['performance']['cagr']
                sharpe = stock['performance']['sharpe_ratio']
                
                base_weight = quality_score
                cagr_factor = min(cagr / 100, 0.5)
                sharpe_factor = min(sharpe / 5, 0.3)
                
                weight = base_weight * (1 + cagr_factor) * (1 + sharpe_factor)
                weights.append(weight)
            
            total_weight = sum(weights)
            normalized_weights = [w / total_weight for w in weights]
            
            total_allocated = 0
            
            for idx, stock in enumerate(self.top_20_stocks):
                current_price = stock['current_price']
                
                target_allocation = self.investment_capital * normalized_weights[idx]
                shares_to_buy = max(int(target_allocation / current_price), 1)
                actual_investment = shares_to_buy * current_price
                
                expected_return_30d = actual_investment * (stock['potential_gain_30d'] / 100)
                expected_return_90d = actual_investment * (stock['potential_gain_90d'] / 100)
                
                allocation = {
                    'allocation_percentage': float(normalized_weights[idx] * 100),
                    'investment_amount': float(actual_investment),
                    'shares_to_buy': int(shares_to_buy),
                    'expected_return_30d': float(expected_return_30d),
                    'expected_return_90d': float(expected_return_90d),
                    'exit_value_30d': float(actual_investment + expected_return_30d),
                    'exit_value_90d': float(actual_investment + expected_return_90d),
                    'roi_30d': float((expected_return_30d / actual_investment) * 100),
                    'roi_90d': float((expected_return_90d / actual_investment) * 100)
                }
                
                stock['allocation'] = allocation
                total_allocated += actual_investment
            
            remaining = self.investment_capital - total_allocated
            
            if remaining > 100:
                print(f"Distributing remaining ₹{remaining:,.2f} to top {min(5, len(self.top_20_stocks))} stocks...\n")
                
                top_n = min(5, len(self.top_20_stocks))
                for stock in self.top_20_stocks[:top_n]:
                    if remaining <= 0:
                        break
                    
                    current_price = stock['current_price']
                    additional_shares = int(remaining / (current_price * top_n))
                    
                    if additional_shares > 0:
                        additional_investment = additional_shares * current_price
                        
                        if additional_investment <= remaining:
                            stock['allocation']['shares_to_buy'] += additional_shares
                            stock['allocation']['investment_amount'] += additional_investment
                            
                            new_amount = stock['allocation']['investment_amount']
                            stock['allocation']['expected_return_30d'] = new_amount * (stock['potential_gain_30d'] / 100)
                            stock['allocation']['expected_return_90d'] = new_amount * (stock['potential_gain_90d'] / 100)
                            stock['allocation']['exit_value_30d'] = new_amount + stock['allocation']['expected_return_30d']
                            stock['allocation']['exit_value_90d'] = new_amount + stock['allocation']['expected_return_90d']
                            stock['allocation']['roi_30d'] = (stock['allocation']['expected_return_30d'] / new_amount) * 100
                            stock['allocation']['roi_90d'] = (stock['allocation']['expected_return_90d'] / new_amount) * 100
                            
                            total_allocated += additional_investment
                            remaining -= additional_investment
            
            final_remaining = self.investment_capital - total_allocated
            utilization = (total_allocated / self.investment_capital) * 100
            
            print(f"{'='*80}")
            print(f"ALLOCATION SUMMARY")
            print(f"{'='*80}")
            print(f"Total Capital: ₹{self.investment_capital:,.2f}")
            print(f"Amount Invested: ₹{total_allocated:,.2f}")
            print(f"Remaining: ₹{final_remaining:,.2f}")
            print(f"Capital Utilization: {utilization:.2f}%")
            print(f"Number of Stocks: {len(self.top_20_stocks)}")
            
            total_return_30d = sum(s['allocation']['expected_return_30d'] for s in self.top_20_stocks)
            total_return_90d = sum(s['allocation']['expected_return_90d'] for s in self.top_20_stocks)
            
            print(f"\nExpected Returns (30 days): ₹{total_return_30d:,.2f} ({(total_return_30d/total_allocated)*100:.2f}%)")
            print(f"Expected Returns (90 days): ₹{total_return_90d:,.2f} ({(total_return_90d/total_allocated)*100:.2f}%)")
            print(f"{'='*80}\n")
            
            print("TOP 20 STOCKS - INVESTMENT BREAKDOWN:")
            print("="*80)
            
            for i, stock in enumerate(self.top_20_stocks, 1):
                alloc = stock['allocation']
                quality = stock['quality']
                perf = stock['performance']
                
                print(f"\n{i}. {stock['name']} ({stock['symbol'].replace('.NS', '')})")
                print(f"   Sector: {stock['sector']} | Rating: {quality['rating']} | Score: {quality['quality_score']}/100")
                print(f"   Price: ₹{stock['current_price']:.2f} | 2Y Return: {perf['return_2y']:+.1f}% | CAGR: {perf['cagr']:.1f}%")
                print(f"   💰 INVEST: ₹{alloc['investment_amount']:,.0f} ({alloc['allocation_percentage']:.1f}%) - {alloc['shares_to_buy']} shares")
                print(f"   📈 30-Day Target: ₹{stock['target_30d']:.2f} | Expected: ₹{alloc['expected_return_30d']:,.0f} ({alloc['roi_30d']:.1f}%)")
                print(f"   📊 90-Day Target: ₹{stock['target_90d']:.2f} | Expected: ₹{alloc['expected_return_90d']:,.0f} ({alloc['roi_90d']:.1f}%)")
            
        except Exception as e:
            print(f"Error in allocation: {str(e)}")
            import traceback
            traceback.print_exc()
    
    def create_stock_chart(self, stock, rank):
        try:
            fig = plt.figure(figsize=(18, 11))
            fig.patch.set_facecolor('#F5F5F5')
            
            hist = stock['history']
            perf = stock['performance']
            indicators = stock['indicators']
            quality = stock['quality']
            allocation = stock['allocation']
            
            gs = fig.add_gridspec(4, 2, height_ratios=[2, 1, 1, 1], hspace=0.35, wspace=0.3)
            
            ax_price = fig.add_subplot(gs[0, :])
            ax_price.plot(hist.index, hist['Close'], color='#00A3E0', linewidth=3, label='Price', zorder=5)
            
            sma_50 = hist['Close'].rolling(window=50).mean()
            sma_200 = hist['Close'].rolling(window=200).mean()
            ax_price.plot(hist.index, sma_50, color='#86BC25', linewidth=2, linestyle='--', label='SMA 50', alpha=0.8)
            ax_price.plot(hist.index, sma_200, color='#FF9800', linewidth=2, linestyle='--', label='SMA 200', alpha=0.8)
            
            ax_price.axhline(y=stock['target_30d'], color='#4CAF50', linestyle=':', 
                            linewidth=2.5, label='30-Day Target', alpha=0.9)
            ax_price.axhline(y=stock['target_90d'], color='#2E7D32', linestyle=':', 
                            linewidth=2.5, label='90-Day Target', alpha=0.9)
            ax_price.axhline(y=stock['stop_loss'], color='#FF4444', linestyle=':', 
                            linewidth=2.5, label='Stop Loss', alpha=0.9)
            
            ax_price.set_title(f"#{rank}. {stock['name']} ({stock['symbol'].replace('.NS', '')})\n"
                              f"2-Year Analysis | Quality Score: {quality['quality_score']}/100 | Rating: {quality['rating']}",
                              fontsize=16, fontweight='bold', pad=15)
            ax_price.set_ylabel('Price (₹)', fontsize=12, fontweight='bold')
            ax_price.legend(loc='upper left', fontsize=10, framealpha=0.95, ncol=3)
            ax_price.grid(True, alpha=0.3, linestyle=':')
            ax_price.set_facecolor('#FFFFFF')
            
            ax_volume = fig.add_subplot(gs[1, :], sharex=ax_price)
            colors = ['#00CC88' if hist['Close'].iloc[i] >= hist['Open'].iloc[i] else '#FF4444' 
                     for i in range(len(hist))]
            ax_volume.bar(hist.index, hist['Volume'], color=colors, alpha=0.6, width=1.5)
            ax_volume.set_ylabel('Volume', fontsize=10, fontweight='bold')
            ax_volume.grid(True, alpha=0.2, linestyle=':')
            ax_volume.set_facecolor('#FFFFFF')
            
            ax_perf = fig.add_subplot(gs[2, 0])
            ax_perf.axis('off')
            
            perf_text = f"📊 PERFORMANCE METRICS\n"
            perf_text += f"{'='*40}\n"
            perf_text += f"Current Price: ₹{stock['current_price']:.2f}\n"
            perf_text += f"2-Year Return: {perf['return_2y']:+.1f}%\n"
            perf_text += f"1-Year Return: {perf['return_1y']:+.1f}%\n"
            perf_text += f"6-Month Return: {perf['return_6m']:+.1f}%\n"
            perf_text += f"3-Month Return: {perf['return_3m']:+.1f}%\n"
            perf_text += f"CAGR: {perf['cagr']:.2f}%\n\n"
            perf_text += f"📈 RISK METRICS\n"
            perf_text += f"{'='*40}\n"
            perf_text += f"Volatility: {perf['volatility']:.1f}%\n"
            perf_text += f"Sharpe Ratio: {perf['sharpe_ratio']:.2f}\n"
            perf_text += f"Max Drawdown: {perf['max_drawdown']:.1f}%\n"
            perf_text += f"Win Rate: {perf['win_rate']:.1f}%"
            
            ax_perf.text(0.05, 0.95, perf_text, transform=ax_perf.transAxes,
                        fontsize=9, verticalalignment='top', fontfamily='monospace',
                        bbox=dict(boxstyle='round', facecolor='#E8F5E9', 
                                edgecolor='#86BC25', linewidth=2, pad=15))
            
            ax_tech = fig.add_subplot(gs[2, 1])
            ax_tech.axis('off')
            
            tech_text = f"⚙️ TECHNICAL INDICATORS\n"
            tech_text += f"{'='*40}\n"
            tech_text += f"RSI: {indicators['rsi']:.1f}\n"
            tech_text += f"MACD: {indicators['macd']:.2f}\n"
            tech_text += f"ADX: {indicators['adx']:.1f}\n"
            tech_text += f"SMA 20: ₹{indicators['sma_20']:.2f}\n"
            tech_text += f"SMA 50: ₹{indicators['sma_50']:.2f}\n"
            tech_text += f"SMA 200: ₹{indicators['sma_200']:.2f}\n\n"
            tech_text += f"📍 LEVELS\n"
            tech_text += f"{'='*40}\n"
            tech_text += f"52W High: ₹{indicators['resistance_52w']:.2f}\n"
            tech_text += f"52W Low: ₹{indicators['support_52w']:.2f}\n"
            tech_text += f"BB Upper: ₹{indicators['bb_upper']:.2f}\n"
            tech_text += f"BB Lower: ₹{indicators['bb_lower']:.2f}\n"
            tech_text += f"Volume Ratio: {indicators['volume_ratio']:.2f}x"
            
            ax_tech.text(0.05, 0.95, tech_text, transform=ax_tech.transAxes,
                        fontsize=9, verticalalignment='top', fontfamily='monospace',
                        bbox=dict(boxstyle='round', facecolor='#E3F2FD', 
                                edgecolor='#00A3E0', linewidth=2, pad=15))
            
            ax_invest = fig.add_subplot(gs[3, 0])
            ax_invest.axis('off')
            
            invest_text = f"💰 INVESTMENT PLAN\n"
            invest_text += f"{'='*40}\n"
            invest_text += f"Allocation: {allocation['allocation_percentage']:.2f}%\n"
            invest_text += f"Amount: ₹{allocation['investment_amount']:,.0f}\n"
            invest_text += f"Shares: {allocation['shares_to_buy']}\n"
            invest_text += f"Entry Price: ₹{stock['current_price']:.2f}\n"
            invest_text += f"Stop Loss: ₹{stock['stop_loss']:.2f}\n\n"
            invest_text += f"📅 30-DAY PLAN\n"
            invest_text += f"{'='*40}\n"
            invest_text += f"Target: ₹{stock['target_30d']:.2f}\n"
            invest_text += f"Expected: ₹{allocation['expected_return_30d']:,.0f}\n"
            invest_text += f"ROI: {allocation['roi_30d']:.1f}%\n"
            invest_text += f"Exit Value: ₹{allocation['exit_value_30d']:,.0f}\n\n"
            invest_text += f"📅 90-DAY PLAN\n"
            invest_text += f"{'='*40}\n"
            invest_text += f"Target: ₹{stock['target_90d']:.2f}\n"
            invest_text += f"Expected: ₹{allocation['expected_return_90d']:,.0f}\n"
            invest_text += f"ROI: {allocation['roi_90d']:.1f}%\n"
            invest_text += f"Exit Value: ₹{allocation['exit_value_90d']:,.0f}"
            
            ax_invest.text(0.05, 0.95, invest_text, transform=ax_invest.transAxes,
                          fontsize=9, verticalalignment='top', fontfamily='monospace',
                          bbox=dict(boxstyle='round', facecolor='#FFF3E0', 
                                  edgecolor='#FF9800', linewidth=2, pad=15))
            
            ax_signals = fig.add_subplot(gs[3, 1])
            ax_signals.axis('off')
            
            signals_text = f"⭐ QUALITY ANALYSIS\n"
            signals_text += f"{'='*40}\n"
            signals_text += f"Overall Score: {quality['quality_score']}/100\n"
            signals_text += f"Rating: {quality['rating']}\n"
            signals_text += f"Confidence: {quality['confidence']:.1f}%\n\n"
            signals_text += f"📋 KEY SIGNALS\n"
            signals_text += f"{'='*40}\n"
            for i, signal in enumerate(quality['signals'][:6], 1):
                signals_text += f"{i}. {signal}\n"
            
            ax_signals.text(0.05, 0.95, signals_text, transform=ax_signals.transAxes,
                           fontsize=8, verticalalignment='top', fontfamily='monospace',
                           bbox=dict(boxstyle='round', facecolor='#F3E5F5', 
                                   edgecolor='#9C27B0', linewidth=2, pad=15))
            
            disclaimer = f"⚠️ Based on 2-year analysis ({len(hist)} trading days) | Educational analysis only | Not financial advice | Past performance ≠ future results"
            fig.text(0.5, 0.01, disclaimer, ha='center', fontsize=8, style='italic', 
                    color='#666666', wrap=True)
            
            filename = os.path.join(self.output_folder, 
                                   f"{rank:02d}_{stock['symbol'].replace('.NS', '')}_2year_analysis.png")
            plt.savefig(filename, dpi=300, bbox_inches='tight', facecolor='#F5F5F5')
            plt.close()
            
            return filename
        except Exception as e:
            print(f"Error creating chart: {str(e)}")
            return None
    
    def create_excel_report(self):
        if not OPENPYXL_AVAILABLE or not self.top_20_stocks:
            return
        
        try:
            filename = os.path.join(self.output_folder, 
                                   f'Top20_Investment_Report_{self.today.strftime("%Y%m%d_%H%M")}.xlsx')
            
            wb = Workbook()
            
            # Summary sheet
            wb = Workbook()
            
            # Summary sheet
            ws_summary = wb.active
            ws_summary.title = "Portfolio Summary"
            
            ws_summary['A1'] = "TOP 20 STOCKS - 2-YEAR ANALYSIS REPORT"
            ws_summary['A1'].font = Font(size=16, bold=True, color='FFFFFF')
            ws_summary['A1'].fill = PatternFill(start_color='86BC25', end_color='86BC25', fill_type='solid')
            ws_summary['A1'].alignment = Alignment(horizontal='center', vertical='center')
            ws_summary.merge_cells('A1:F1')
            ws_summary.row_dimensions[1].height = 30
            
            ws_summary['A3'] = f"Analysis Period: {self.two_years_ago.strftime('%d %b %Y')} to {self.today.strftime('%d %b %Y')}"
            ws_summary['A3'].font = Font(size=11, italic=True)
            ws_summary.merge_cells('A3:F3')
            
            total_invested = sum(s['allocation']['investment_amount'] for s in self.top_20_stocks)
            total_return_30d = sum(s['allocation']['expected_return_30d'] for s in self.top_20_stocks)
            total_return_90d = sum(s['allocation']['expected_return_90d'] for s in self.top_20_stocks)
            avg_score = sum(s['quality']['quality_score'] for s in self.top_20_stocks) / len(self.top_20_stocks)
            avg_cagr = sum(s['performance']['cagr'] for s in self.top_20_stocks) / len(self.top_20_stocks)
            
            summary_data = [
                ['Total Investment Capital', f"₹{self.investment_capital:,.2f}"],
                ['Amount Invested', f"₹{total_invested:,.2f}"],
                ['Capital Utilization', f"{(total_invested/self.investment_capital)*100:.2f}%"],
                ['Number of Stocks', str(len(self.top_20_stocks))],
                ['Average Quality Score', f"{avg_score:.1f}/100"],
                ['Average CAGR', f"{avg_cagr:.2f}%"],
                ['Expected Return (30 days)', f"₹{total_return_30d:,.2f}"],
                ['Expected ROI (30 days)', f"{(total_return_30d/total_invested)*100:.2f}%"],
                ['Expected Return (90 days)', f"₹{total_return_90d:,.2f}"],
                ['Expected ROI (90 days)', f"{(total_return_90d/total_invested)*100:.2f}%"]
            ]
            
            start_row = 5
            for i, (label, value) in enumerate(summary_data, start=start_row):
                ws_summary[f'A{i}'] = label
                ws_summary[f'A{i}'].font = Font(bold=True)
                ws_summary[f'B{i}'] = value
                ws_summary[f'B{i}'].font = Font(size=11)
                ws_summary[f'A{i}'].fill = PatternFill(start_color='E8F5E9', end_color='E8F5E9', fill_type='solid')
                ws_summary[f'B{i}'].fill = PatternFill(start_color='FFFFFF', end_color='FFFFFF', fill_type='solid')
            
            ws_summary.column_dimensions['A'].width = 30
            ws_summary.column_dimensions['B'].width = 25
            
            # Details sheet
            ws_details = wb.create_sheet(title="Investment Details")
            
            headers = ['Rank', 'Company', 'Symbol', 'Sector', 'Price', 'Score', 'Rating',
                      'Allocation%', 'Invest Amount', 'Shares', '2Y Return%', 'CAGR%', 
                      'Sharpe', '30D Target', '30D Expected', '30D ROI%', 
                      '90D Target', '90D Expected', '90D ROI%', 'Stop Loss']
            
            for col, header in enumerate(headers, start=1):
                cell = ws_details.cell(row=1, column=col, value=header)
                cell.font = Font(bold=True, color='FFFFFF', size=11)
                cell.fill = PatternFill(start_color='00A3E0', end_color='00A3E0', fill_type='solid')
                cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
            
            for idx, stock in enumerate(self.top_20_stocks, start=2):
                perf = stock['performance']
                quality = stock['quality']
                allocation = stock['allocation']
                
                row_data = [
                    idx - 1,
                    stock['name'],
                    stock['symbol'].replace('.NS', ''),
                    stock['sector'],
                    f"₹{stock['current_price']:.2f}",
                    quality['quality_score'],
                    quality['rating'],
                    f"{allocation['allocation_percentage']:.2f}%",
                    f"₹{allocation['investment_amount']:,.2f}",
                    allocation['shares_to_buy'],
                    f"{perf['return_2y']:.1f}%",
                    f"{perf['cagr']:.2f}%",
                    f"{perf['sharpe_ratio']:.2f}",
                    f"₹{stock['target_30d']:.2f}",
                    f"₹{allocation['expected_return_30d']:,.2f}",
                    f"{allocation['roi_30d']:.1f}%",
                    f"₹{stock['target_90d']:.2f}",
                    f"₹{allocation['expected_return_90d']:,.2f}",
                    f"{allocation['roi_90d']:.1f}%",
                    f"₹{stock['stop_loss']:.2f}"
                ]
                
                for col, value in enumerate(row_data, start=1):
                    cell = ws_details.cell(row=idx, column=col, value=value)
                    cell.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
                    
                    if idx % 2 == 0:
                        cell.fill = PatternFill(start_color='F5F5F5', end_color='F5F5F5', fill_type='solid')
                    
                    if col == 7:
                        if value == 'EXCELLENT':
                            cell.fill = PatternFill(start_color='A5D6A7', end_color='A5D6A7', fill_type='solid')
                            cell.font = Font(bold=True, color='1B5E20')
                        elif value == 'VERY GOOD':
                            cell.fill = PatternFill(start_color='C8E6C9', end_color='C8E6C9', fill_type='solid')
                            cell.font = Font(bold=True, color='2E7D32')
            
            for col in range(1, len(headers) + 1):
                ws_details.column_dimensions[ws_details.cell(row=1, column=col).column_letter].width = 15
            
            ws_details.column_dimensions['B'].width = 30
            ws_details.column_dimensions['D'].width = 20
            
            # Performance comparison sheet
            ws_perf = wb.create_sheet(title="Performance Analysis")
            
            ws_perf['A1'] = "PERFORMANCE COMPARISON - 2 YEAR DATA"
            ws_perf['A1'].font = Font(size=14, bold=True, color='FFFFFF')
            ws_perf['A1'].fill = PatternFill(start_color='FF9800', end_color='FF9800', fill_type='solid')
            ws_perf['A1'].alignment = Alignment(horizontal='center', vertical='center')
            ws_perf.merge_cells('A1:L1')
            
            perf_headers = ['Rank', 'Stock', '2Y Return%', '1Y Return%', '6M Return%', 
                           '3M Return%', '1M Return%', 'CAGR%', 'Volatility%', 
                           'Sharpe Ratio', 'Max Drawdown%', 'Win Rate%']
            
            for col, header in enumerate(perf_headers, start=1):
                cell = ws_perf.cell(row=3, column=col, value=header)
                cell.font = Font(bold=True, size=11)
                cell.fill = PatternFill(start_color='FFE0B2', end_color='FFE0B2', fill_type='solid')
                cell.alignment = Alignment(horizontal='center', vertical='center')
            
            for idx, stock in enumerate(self.top_20_stocks, start=4):
                perf = stock['performance']
                
                perf_data = [
                    idx - 3,
                    stock['symbol'].replace('.NS', ''),
                    f"{perf['return_2y']:.1f}%",
                    f"{perf['return_1y']:.1f}%",
                    f"{perf['return_6m']:.1f}%",
                    f"{perf['return_3m']:.1f}%",
                    f"{perf['return_1m']:.1f}%",
                    f"{perf['cagr']:.2f}%",
                    f"{perf['volatility']:.1f}%",
                    f"{perf['sharpe_ratio']:.2f}",
                    f"{perf['max_drawdown']:.1f}%",
                    f"{perf['win_rate']:.1f}%"
                ]
                
                for col, value in enumerate(perf_data, start=1):
                    cell = ws_perf.cell(row=idx, column=col, value=value)
                    cell.alignment = Alignment(horizontal='center', vertical='center')
                    
                    if idx % 2 == 0:
                        cell.fill = PatternFill(start_color='FFF8E1', end_color='FFF8E1', fill_type='solid')
                    
                    if col == 3:
                        try:
                            return_val = float(value.replace('%', ''))
                            if return_val > 100:
                                cell.fill = PatternFill(start_color='C8E6C9', end_color='C8E6C9', fill_type='solid')
                                cell.font = Font(bold=True, color='1B5E20')
                        except:
                            pass
            
            for col in range(1, len(perf_headers) + 1):
                ws_perf.column_dimensions[ws_perf.cell(row=3, column=col).column_letter].width = 14
            
            ws_perf.column_dimensions['B'].width = 18
            
            # Technical indicators sheet
            ws_tech = wb.create_sheet(title="Technical Indicators")
            
            ws_tech['A1'] = "TECHNICAL ANALYSIS - CURRENT INDICATORS"
            ws_tech['A1'].font = Font(size=14, bold=True, color='FFFFFF')
            ws_tech['A1'].fill = PatternFill(start_color='00A3E0', end_color='00A3E0', fill_type='solid')
            ws_tech['A1'].alignment = Alignment(horizontal='center', vertical='center')
            ws_tech.merge_cells('A1:K1')
            
            tech_headers = ['Rank', 'Stock', 'RSI', 'MACD', 'ADX', 'SMA 50', 'SMA 200',
                           'Volume Ratio', 'BB Width%', 'Support', 'Resistance']
            
            for col, header in enumerate(tech_headers, start=1):
                cell = ws_tech.cell(row=3, column=col, value=header)
                cell.font = Font(bold=True, size=11)
                cell.fill = PatternFill(start_color='E3F2FD', end_color='E3F2FD', fill_type='solid')
                cell.alignment = Alignment(horizontal='center', vertical='center')
            
            for idx, stock in enumerate(self.top_20_stocks, start=4):
                indicators = stock['indicators']
                
                tech_data = [
                    idx - 3,
                    stock['symbol'].replace('.NS', ''),
                    f"{indicators['rsi']:.1f}",
                    f"{indicators['macd']:.2f}",
                    f"{indicators['adx']:.1f}",
                    f"₹{indicators['sma_50']:.2f}",
                    f"₹{indicators['sma_200']:.2f}",
                    f"{indicators['volume_ratio']:.2f}x",
                    f"{indicators['bb_width']:.1f}%",
                    f"₹{indicators['support_52w']:.2f}",
                    f"₹{indicators['resistance_52w']:.2f}"
                ]
                
                for col, value in enumerate(tech_data, start=1):
                    cell = ws_tech.cell(row=idx, column=col, value=value)
                    cell.alignment = Alignment(horizontal='center', vertical='center')
                    
                    if idx % 2 == 0:
                        cell.fill = PatternFill(start_color='F5F5F5', end_color='F5F5F5', fill_type='solid')
                    
                    if col == 3:
                        try:
                            rsi_val = float(value)
                            if rsi_val < 35:
                                cell.fill = PatternFill(start_color='FFCDD2', end_color='FFCDD2', fill_type='solid')
                                cell.font = Font(color='C62828')
                            elif 40 <= rsi_val <= 60:
                                cell.fill = PatternFill(start_color='C8E6C9', end_color='C8E6C9', fill_type='solid')
                                cell.font = Font(color='2E7D32')
                        except:
                            pass
            
            for col in range(1, len(tech_headers) + 1):
                ws_tech.column_dimensions[ws_tech.cell(row=3, column=col).column_letter].width = 14
            
            ws_tech.column_dimensions['B'].width = 18
            
            wb.save(filename)
            print(f"\n✓ Comprehensive Excel report saved: '{filename}'")
            print(f"  • Portfolio Summary sheet")
            print(f"  • Investment Details sheet (Top 20)")
            print(f"  • Performance Analysis sheet")
            print(f"  • Technical Indicators sheet")
            return filename
            
        except Exception as e:
            print(f"✗ Error creating Excel: {str(e)}")
            import traceback
            traceback.print_exc()
            return None
    
    def generate_all_reports(self):
        if not self.top_20_stocks:
            print("\n⚠️  No stocks to report.")
            return
        
        print(f"\n\n{'='*80}")
        print(f"GENERATING COMPREHENSIVE REPORTS")
        print(f"{'='*80}\n")
        
        print("Creating individual stock charts (Top 20)...")
        chart_count = 0
        for idx, stock in enumerate(self.top_20_stocks, 1):
            print(f"  [{idx}/20] {stock['name']}...", end=' ')
            chart_file = self.create_stock_chart(stock, idx)
            if chart_file:
                print("✓")
                chart_count += 1
            else:
                print("✗")
        
        print(f"\n{'='*80}")
        print(f"GENERATING EXCEL REPORT WITH 4 SHEETS")
        print(f"{'='*80}\n")
        
        excel_file = self.create_excel_report()
        
        if excel_file or chart_count > 0:
            print(f"\n{'='*80}")
            print(f"✅ REPORTS GENERATED SUCCESSFULLY!")
            print(f"{'='*80}")
            print(f"\n📁 Output Folder: {self.output_folder}")
            print(f"\n📊 What's Included:")
            
            if chart_count > 0:
                print(f"   • {chart_count} Individual Stock Charts (PNG files)")
                print(f"     - 2-year price history")
                print(f"     - Performance metrics")
                print(f"     - Technical indicators")
                print(f"     - Investment plan with exact amounts")
            
            if excel_file:
                print(f"\n   • 1 Comprehensive Excel Report (XLSX file)")
                print(f"     - Portfolio Summary")
                print(f"     - Investment Details (all {len(self.top_20_stocks)} stocks)")
                print(f"     - Performance Comparison")
                print(f"     - Technical Indicators")
            
            print(f"\n💡 Next Steps:")
            print(f"   1. Review Excel report for portfolio overview")
            print(f"   2. Check individual charts for each stock")
            print(f"   3. Note exact investment amounts per stock")
            print(f"   4. Set up tracking for 30-day and 90-day targets")
            print(f"   5. Configure stop-loss orders as indicated")
            print(f"{'='*80}\n")

def main():
    print("\n" + "="*80)
    print("   📊 2-YEAR STOCK ANALYSIS & TOP 20 INVESTMENT PICKER")
    print("   Deep Historical Analysis with Excel Reports & Charts")
    print("="*80 + "\n")
    
    print("This script will:")
    print("  ✓ Fetch 2 years of historical data from 100+ NSE stocks")
    print("  ✓ Use ROBUST price extraction (multiple fallback methods)")
    print("  ✓ Analyze performance metrics (CAGR, Sharpe, Drawdown, etc.)")
    print("  ✓ Calculate technical indicators (RSI, MACD, ADX, etc.)")
    print("  ✓ Score stocks on 100-point quality scale")
    print("  ✓ Select TOP 20 stocks based on comprehensive analysis")
    print("  ✓ Allocate 100% of your capital with exact amounts per stock")
    print("  ✓ Generate Excel report (4 sheets) + individual charts\n")
    
    try:
        capital = input("Enter investment capital (default ₹1,00,000): ").strip()
        if capital and capital.replace(',', '').replace('.', '').isdigit():
            capital = float(capital.replace(',', ''))
        else:
            capital = 100000
        
        print(f"\n✓ Investment Capital: ₹{capital:,.2f}")
        print(f"✓ Analysis Period: 2 years (730 days)")
        print(f"✓ Target: Top 20 stocks")
        print(f"\n⏳ Starting comprehensive analysis...")
        print("   This will take 3-5 minutes due to 2-year data collection\n")
        
        analyzer = TwoYearStockAnalyzer(investment_capital=capital)
        
        print(f"📂 Output folder: {analyzer.output_folder}\n")
        
        # Fetch 2-year data with robust price extraction
        analyzer.fetch_2year_data()
        
        if not analyzer.stock_data:
            print("\n✗ Failed to fetch stock data. Please check your internet connection.")
            print("\nTroubleshooting Tips:")
            print("1. Check internet connection")
            print("2. Try during market hours (9:15 AM - 3:30 PM IST)")
            print("3. Update yfinance: pip install --upgrade yfinance")
            print("4. Wait a few minutes and try again")
            return
        
        # Analyze all stocks
        analyzer.analyze_all_stocks()
        
        if not analyzer.top_20_stocks:
            print("\n✗ Analysis failed. No stocks qualified.")
            return
        
        # Show final summary
        total_invested = sum(s['allocation']['investment_amount'] for s in analyzer.top_20_stocks)
        total_return_30d = sum(s['allocation']['expected_return_30d'] for s in analyzer.top_20_stocks)
        total_return_90d = sum(s['allocation']['expected_return_90d'] for s in analyzer.top_20_stocks)
        avg_cagr = sum(s['performance']['cagr'] for s in analyzer.top_20_stocks) / len(analyzer.top_20_stocks)
        
        print(f"\n{'='*80}")
        print(f"FINAL PORTFOLIO SUMMARY")
        print(f"{'='*80}")
        print(f"Investment Capital: ₹{capital:,.2f}")
        print(f"Amount Deployed: ₹{total_invested:,.2f}")
        print(f"Capital Utilization: {(total_invested/capital)*100:.2f}%")
        print(f"Number of Stocks: {len(analyzer.top_20_stocks)}")
        print(f"Average CAGR: {avg_cagr:.2f}%")
        print(f"\n📈 EXPECTED RETURNS:")
        print(f"  30-Day: ₹{total_return_30d:,.2f} ({(total_return_30d/total_invested)*100:.2f}% ROI)")
        print(f"  90-Day: ₹{total_return_90d:,.2f} ({(total_return_90d/total_invested)*100:.2f}% ROI)")
        print(f"{'='*80}\n")
        
        # Ask to generate reports
        generate = input("Generate detailed reports (Excel + Charts)? (y/n): ").strip().lower()
        if generate == 'y':
            analyzer.generate_all_reports()
            
            # Try to open folder
            import platform
            if platform.system() == 'Windows':
                try:
                    os.startfile(analyzer.output_folder)
                except:
                    print(f"\nPlease manually open: {analyzer.output_folder}")
            elif platform.system() == 'Darwin':
                os.system(f'open "{analyzer.output_folder}"')
            else:
                os.system(f'xdg-open "{analyzer.output_folder}"')
        else:
            print("\n✓ Analysis complete. Reports not generated.")
        
        # Show disclaimer
        print("\n" + "="*80)
        print("⚠️  CRITICAL DISCLAIMER")
        print("="*80)
        print("This analysis is based on HISTORICAL data (past 2 years).")
        print("Past performance does NOT guarantee future results.")
        print("\n🚨 BEFORE INVESTING:")
        print("1. This is EDUCATIONAL ANALYSIS ONLY, not financial advice")
        print("2. Consult a SEBI-registered financial advisor")
        print("3. Conduct your own due diligence (DYOR)")
        print("4. Understand your risk tolerance and investment goals")
        print("5. Never invest money you cannot afford to lose")
        print("6. Markets are unpredictable - use stop-losses")
        print("7. Diversify across asset classes, not just stocks")
        print("8. Review company fundamentals before investing")
        print("9. Monitor investments regularly")
        print("10. Stay informed about market conditions and news")
        print("\n📊 ANALYSIS METHODOLOGY:")
        print("• Quality Score: Weighted average of performance, technical, risk, and consistency")
        print("• Allocation: Based on quality score, CAGR, and Sharpe ratio")
        print("• Targets: Based on historical momentum and technical levels")
        print("• Stop-loss: Conservative 8% below entry or support level")
        print("="*80 + "\n")
    
    except KeyboardInterrupt:
        print("\n\n⚠️  Analysis interrupted by user")
    except Exception as e:
        print(f"\n✗ An error occurred: {str(e)}")
        import traceback
        traceback.print_exc()

if __name__ == '__main__':
    main()